
// Generated by 'Automation/update_country_flags.py'
public extension CountryFlag {

    enum CountryCode: String, CaseIterable {

        /// Country code for Andorra
        case ad

        /// Country code for United Arab Emirates
        case ae

        /// Country code for Afghanistan
        case af

        /// Country code for Antigua and Barbuda
        case ag

        /// Country code for Anguilla
        case ai

        /// Country code for Albania
        case al

        /// Country code for Armenia
        case am

        /// Country code for Netherlands Antilles
        case an

        /// Country code for Angola
        case ao

        /// Country code for Antarctica
        case aq

        /// Country code for Argentina
        case ar

        /// Country code for American Samoa
        case `as`

        /// Country code for Austria
        case at

        /// Country code for Australia
        case au

        /// Country code for Aruba
        case aw

        /// Country code for Åland Islands
        case ax

        /// Country code for Azerbaijan
        case az

        /// Country code for Bosnia and Herzegovina
        case ba

        /// Country code for Barbados
        case bb

        /// Country code for Bangladesh
        case bd

        /// Country code for Belgium
        case be

        /// Country code for Burkina Faso
        case bf

        /// Country code for Bulgaria
        case bg

        /// Country code for Bahrain
        case bh

        /// Country code for Burundi
        case bi

        /// Country code for Benin
        case bj

        /// Country code for Saint Barthélemy
        case bl

        /// Country code for Bermuda
        case bm

        /// Country code for Brunei
        case bn

        /// Country code for Bolivia
        case bo

        case bq

        /// Country code for Brazil
        case br

        /// Country code for Bahamas
        case bs

        /// Country code for Bhutan
        case bt

        case bv

        /// Country code for Botswana
        case bw

        /// Country code for Belarus
        case by

        /// Country code for Belize
        case bz

        /// Country code for Canada
        case ca

        case caFr

        /// Country code for Cocos [Keeling] Islands
        case cc

        /// Country code for Congo - Kinshasa
        case cd

        /// Country code for Central African Republic
        case cf

        /// Country code for Congo - Brazzaville
        case cg

        /// Country code for Switzerland
        case ch

        /// Country code for Côte d’Ivoire
        case ci

        /// Country code for Cook Islands
        case ck

        /// Country code for Chile
        case cl

        /// Country code for Cameroon
        case cm

        /// Country code for China
        case cn

        /// Country code for Colombia
        case co

        /// Country code for Costa Rica
        case cr

        case cs

        case ct

        case cu

        /// Country code for Cape Verde
        case cv

        case cw

        /// Country code for Christmas Island
        case cx

        /// Country code for Cyprus
        case cy

        /// Country code for Czech Republic
        case cz

        /// Country code for Germany
        case de

        /// Country code for Djibouti
        case dj

        /// Country code for Denmark
        case dk

        /// Country code for Dominica
        case dm

        /// Country code for Dominican Republic
        case `do`

        /// Country code for Algeria
        case dz

        /// Country code for Ecuador
        case ec

        /// Country code for Estonia
        case ee

        /// Country code for Egypt
        case eg

        /// Country code for Western Sahara
        case eh

        /// Country code for Eritrea
        case er

        /// Country code for Spain
        case es

        /// Country code for Ethiopia
        case et

        case eu

        /// Country code for Finland
        case fi

        /// Country code for Fiji
        case fj

        /// Country code for Falkland Islands
        case fk

        /// Country code for Micronesia
        case fm

        /// Country code for Faroe Islands
        case fo

        /// Country code for France
        case fr

        /// Country code for Gabon
        case ga

        /// Country code for United Kingdom
        case gb

        /// Country code for Grenada
        case gd

        /// Country code for Georgia
        case ge

        /// Country code for French Guiana
        case gf

        /// Country code for Guernsey
        case gg

        /// Country code for Ghana
        case gh

        /// Country code for Gibraltar
        case gi

        /// Country code for Greenland
        case gl

        /// Country code for Gambia
        case gm

        /// Country code for Guinea
        case gn

        /// Country code for Guadeloupe
        case gp

        /// Country code for Equatorial Guinea
        case gq

        /// Country code for Greece
        case gr

        /// Country code for South Georgia and the South Sandwich Islands
        case gs

        /// Country code for Guatemala
        case gt

        /// Country code for Guam
        case gu

        /// Country code for Guinea-Bissau
        case gw

        /// Country code for Guyana
        case gy

        /// Country code for Hong Kong SAR China
        case hk

        case hm

        /// Country code for Honduras
        case hn

        /// Country code for Croatia
        case hr

        /// Country code for Haiti
        case ht

        /// Country code for Hungary
        case hu

        case ic

        /// Country code for Indonesia
        case id

        /// Country code for Ireland
        case ie

        /// Country code for Israel
        case il

        /// Country code for Isle of Man
        case im

        /// Country code for India
        case `in`

        /// Country code for British Indian Ocean Territory
        case io

        /// Country code for Iraq
        case iq

        /// Country code for Iran
        case ir

        /// Country code for Iceland
        case `is`

        /// Country code for Italy
        case it

        /// Country code for Jersey
        case je

        /// Country code for Jamaica
        case jm

        /// Country code for Jordan
        case jo

        /// Country code for Japan
        case jp

        /// Country code for Kenya
        case ke

        /// Country code for Kyrgyzstan
        case kg

        /// Country code for Cambodia
        case kh

        /// Country code for Kiribati
        case ki

        /// Country code for Comoros
        case km

        /// Country code for Saint Kitts and Nevis
        case kn

        /// Country code for North Korea
        case kp

        /// Country code for South Korea
        case kr

        /// Country code for Kuwait
        case kw

        /// Country code for Cayman Islands
        case ky

        /// Country code for Kazakhstan
        case kz

        /// Country code for Laos
        case la

        /// Country code for Lebanon
        case lb

        /// Country code for Saint Lucia
        case lc

        /// Country code for Liechtenstein
        case li

        /// Country code for Sri Lanka
        case lk

        /// Country code for Liberia
        case lr

        /// Country code for Lesotho
        case ls

        /// Country code for Lithuania
        case lt

        /// Country code for Luxembourg
        case lu

        /// Country code for Latvia
        case lv

        /// Country code for Libya
        case ly

        /// Country code for Morocco
        case ma

        /// Country code for Monaco
        case mc

        /// Country code for Moldova
        case md

        /// Country code for Montenegro
        case me

        /// Country code for Saint Martin
        case mf

        /// Country code for Madagascar
        case mg

        /// Country code for Marshall Islands
        case mh

        /// Country code for Macedonia
        case mk

        /// Country code for Mali
        case ml

        /// Country code for Myanmar [Burma]
        case mm

        /// Country code for Mongolia
        case mn

        /// Country code for Macau SAR China
        case mo

        /// Country code for Northern Mariana Islands
        case mp

        /// Country code for Martinique
        case mq

        /// Country code for Mauritania
        case mr

        /// Country code for Montserrat
        case ms

        /// Country code for Malta
        case mt

        /// Country code for Mauritius
        case mu

        /// Country code for Maldives
        case mv

        /// Country code for Malawi
        case mw

        /// Country code for Mexico
        case mx

        /// Country code for Malaysia
        case my

        /// Country code for Mozambique
        case mz

        /// Country code for Namibia
        case na

        /// Country code for New Caledonia
        case nc

        /// Country code for Niger
        case ne

        /// Country code for Norfolk Island
        case nf

        /// Country code for Nigeria
        case ng

        /// Country code for Nicaragua
        case ni

        /// Country code for Netherlands
        case nl

        /// Country code for Norway
        case no

        /// Country code for Nepal
        case np

        /// Country code for Nauru
        case nr

        /// Country code for Niue
        case nu

        /// Country code for New Zealand
        case nz

        /// Country code for Oman
        case om

        /// Country code for Panama
        case pa

        /// Country code for Peru
        case pe

        /// Country code for French Polynesia
        case pf

        /// Country code for Papua New Guinea
        case pg

        /// Country code for Philippines
        case ph

        /// Country code for Pakistan
        case pk

        /// Country code for Poland
        case pl

        /// Country code for Saint Pierre and Miquelon
        case pm

        /// Country code for Pitcairn Islands
        case pn

        /// Country code for Puerto Rico
        case pr

        /// Country code for Palestinian Territories
        case ps

        /// Country code for Portugal
        case pt

        /// Country code for Palau
        case pw

        /// Country code for Paraguay
        case py

        /// Country code for Qatar
        case qa

        /// Country code for Réunion
        case re

        /// Country code for Romania
        case ro

        /// Country code for Serbia
        case rs

        /// Country code for Russia
        case ru

        /// Country code for Rwanda
        case rw

        /// Country code for Saudi Arabia
        case sa

        /// Country code for Solomon Islands
        case sb

        /// Country code for Seychelles
        case sc

        /// Country code for Sudan
        case sd

        /// Country code for Sweden
        case se

        /// Country code for Singapore
        case sg

        /// Country code for Saint Helena
        case sh

        /// Country code for Slovenia
        case si

        /// Country code for Svalbard and Jan Mayen
        case sj

        /// Country code for Slovakia
        case sk

        /// Country code for Sierra Leone
        case sl

        /// Country code for San Marino
        case sm

        /// Country code for Senegal
        case sn

        /// Country code for Somalia
        case so

        /// Country code for Suriname
        case sr

        case ss

        /// Country code for São Tomé and Príncipe
        case st

        /// Country code for El Salvador
        case sv

        case sx

        /// Country code for Syria
        case sy

        /// Country code for Swaziland
        case sz

        /// Country code for Turks and Caicos Islands
        case tc

        /// Country code for Chad
        case td

        /// Country code for French Southern Territories
        case tf

        /// Country code for Togo
        case tg

        /// Country code for Thailand
        case th

        /// Country code for Tajikistan
        case tj

        /// Country code for Tokelau
        case tk

        /// Country code for Timor-Leste
        case tl

        /// Country code for Turkmenistan
        case tm

        /// Country code for Tunisia
        case tn

        /// Country code for Tonga
        case to

        /// Country code for Turkey
        case tr

        /// Country code for Trinidad and Tobago
        case tt

        /// Country code for Tuvalu
        case tv

        /// Country code for Taiwan
        case tw

        /// Country code for Tanzania
        case tz

        /// Country code for Ukraine
        case ua

        /// Country code for Uganda
        case ug

        case um

        case unknown

        /// Country code for United States
        case us

        /// Country code for Uruguay
        case uy

        /// Country code for Uzbekistan
        case uz

        /// Country code for Vatican City
        case va

        /// Country code for Saint Vincent and the Grenadines
        case vc

        /// Country code for Venezuela
        case ve

        /// Country code for British Virgin Islands
        case vg

        /// Country code for U.S. Virgin Islands
        case vi

        /// Country code for Vietnam
        case vn

        /// Country code for Vanuatu
        case vu

        /// Country code for Wallis and Futuna
        case wf

        /// Country code for Samoa
        case ws

        case xk

        /// Country code for Yemen
        case ye

        /// Country code for Mayotte
        case yt

        /// Country code for South Africa
        case za

        /// Country code for Zambia
        case zm

        /// Country code for Zimbabwe
        case zw
    }
}
