import SwiftUI

// Generated by 'Automation/update_colors.py'
public extension Color {

    // MARK: - Blue
    /// Orbit Blue Dark color.
    static let blueDark = Color("Blue Dark", bundle: .current)
    /// Orbit Blue Dark Active color.
    static let blueDarkActive = Color("Blue Dark Active", bundle: .current)
    /// Orbit Blue Dark Hover color.
    static let blueDarkHover = Color("Blue Dark Hover", bundle: .current)
    /// Orbit Blue Darker color.
    static let blueDarker = Color("Blue Darker", bundle: .current)
    /// Orbit Blue Light color.
    static let blueLight = Color("Blue Light", bundle: .current)
    /// Orbit Blue Light Active color.
    static let blueLightActive = Color("Blue Light Active", bundle: .current)
    /// Orbit Blue Light Hover color.
    static let blueLightHover = Color("Blue Light Hover", bundle: .current)
    /// Orbit Blue Normal color.
    static let blueNormal = Color("Blue Normal", bundle: .current)
    /// Orbit Blue Normal Active color.
    static let blueNormalActive = Color("Blue Normal Active", bundle: .current)
    /// Orbit Blue Normal Hover color.
    static let blueNormalHover = Color("Blue Normal Hover", bundle: .current)

    // MARK: - Bundle
    /// Orbit Bundle Basic color.
    static let bundleBasic = Color("Bundle Basic", bundle: .current)
    /// Orbit Bundle Medium color.
    static let bundleMedium = Color("Bundle Medium", bundle: .current)

    // MARK: - Cloud
    /// Orbit Cloud Dark color.
    static let cloudDark = Color("Cloud Dark", bundle: .current)
    /// Orbit Cloud Darker color.
    static let cloudDarker = Color("Cloud Darker", bundle: .current)
    /// Orbit Cloud Darker Active color.
    static let cloudDarkerActive = Color("Cloud Darker Active", bundle: .current)
    /// Orbit Cloud Darker Hover color.
    static let cloudDarkerHover = Color("Cloud Darker Hover", bundle: .current)
    /// Orbit Cloud Light color.
    static let cloudLight = Color("Cloud Light", bundle: .current)
    /// Orbit Cloud Light Active color.
    static let cloudLightActive = Color("Cloud Light Active", bundle: .current)
    /// Orbit Cloud Light Hover color.
    static let cloudLightHover = Color("Cloud Light Hover", bundle: .current)
    /// Orbit Cloud Normal color.
    static let cloudNormal = Color("Cloud Normal", bundle: .current)
    /// Orbit Cloud Normal Active color.
    static let cloudNormalActive = Color("Cloud Normal Active", bundle: .current)
    /// Orbit Cloud Normal Hover color.
    static let cloudNormalHover = Color("Cloud Normal Hover", bundle: .current)

    // MARK: - Green
    /// Orbit Green Dark color.
    static let greenDark = Color("Green Dark", bundle: .current)
    /// Orbit Green Dark Active color.
    static let greenDarkActive = Color("Green Dark Active", bundle: .current)
    /// Orbit Green Dark Hover color.
    static let greenDarkHover = Color("Green Dark Hover", bundle: .current)
    /// Orbit Green Darker color.
    static let greenDarker = Color("Green Darker", bundle: .current)
    /// Orbit Green Light color.
    static let greenLight = Color("Green Light", bundle: .current)
    /// Orbit Green Light Active color.
    static let greenLightActive = Color("Green Light Active", bundle: .current)
    /// Orbit Green Light Hover color.
    static let greenLightHover = Color("Green Light Hover", bundle: .current)
    /// Orbit Green Normal color.
    static let greenNormal = Color("Green Normal", bundle: .current)
    /// Orbit Green Normal Active color.
    static let greenNormalActive = Color("Green Normal Active", bundle: .current)
    /// Orbit Green Normal Hover color.
    static let greenNormalHover = Color("Green Normal Hover", bundle: .current)

    // MARK: - Ink
    /// Orbit Ink Light color.
    static let inkLight = Color("Ink Light", bundle: .current)
    /// Orbit Ink Light Active color.
    static let inkLightActive = Color("Ink Light Active", bundle: .current)
    /// Orbit Ink Light Hover color.
    static let inkLightHover = Color("Ink Light Hover", bundle: .current)
    /// Orbit Ink Lighter color.
    static let inkLighter = Color("Ink Lighter", bundle: .current)
    /// Orbit Ink Lighter Active color.
    static let inkLighterActive = Color("Ink Lighter Active", bundle: .current)
    /// Orbit Ink Lighter Hover color.
    static let inkLighterHover = Color("Ink Lighter Hover", bundle: .current)
    /// Orbit Ink Normal color.
    static let inkNormal = Color("Ink Normal", bundle: .current)
    /// Orbit Ink Normal Active color.
    static let inkNormalActive = Color("Ink Normal Active", bundle: .current)
    /// Orbit Ink Normal Hover color.
    static let inkNormalHover = Color("Ink Normal Hover", bundle: .current)

    // MARK: - Orange
    /// Orbit Orange Dark color.
    static let orangeDark = Color("Orange Dark", bundle: .current)
    /// Orbit Orange Dark Active color.
    static let orangeDarkActive = Color("Orange Dark Active", bundle: .current)
    /// Orbit Orange Dark Hover color.
    static let orangeDarkHover = Color("Orange Dark Hover", bundle: .current)
    /// Orbit Orange Darker color.
    static let orangeDarker = Color("Orange Darker", bundle: .current)
    /// Orbit Orange Light color.
    static let orangeLight = Color("Orange Light", bundle: .current)
    /// Orbit Orange Light Active color.
    static let orangeLightActive = Color("Orange Light Active", bundle: .current)
    /// Orbit Orange Light Hover color.
    static let orangeLightHover = Color("Orange Light Hover", bundle: .current)
    /// Orbit Orange Normal color.
    static let orangeNormal = Color("Orange Normal", bundle: .current)
    /// Orbit Orange Normal Active color.
    static let orangeNormalActive = Color("Orange Normal Active", bundle: .current)
    /// Orbit Orange Normal Hover color.
    static let orangeNormalHover = Color("Orange Normal Hover", bundle: .current)

    // MARK: - Product
    /// Orbit Product Dark color.
    static let productDark = Color("Product Dark", bundle: .current)
    /// Orbit Product Dark Active color.
    static let productDarkActive = Color("Product Dark Active", bundle: .current)
    /// Orbit Product Dark Hover color.
    static let productDarkHover = Color("Product Dark Hover", bundle: .current)
    /// Orbit Product Darker color.
    static let productDarker = Color("Product Darker", bundle: .current)
    /// Orbit Product Light color.
    static let productLight = Color("Product Light", bundle: .current)
    /// Orbit Product Light Active color.
    static let productLightActive = Color("Product Light Active", bundle: .current)
    /// Orbit Product Light Hover color.
    static let productLightHover = Color("Product Light Hover", bundle: .current)
    /// Orbit Product Normal color.
    static let productNormal = Color("Product Normal", bundle: .current)
    /// Orbit Product Normal Active color.
    static let productNormalActive = Color("Product Normal Active", bundle: .current)
    /// Orbit Product Normal Hover color.
    static let productNormalHover = Color("Product Normal Hover", bundle: .current)

    // MARK: - Red
    /// Orbit Red Dark color.
    static let redDark = Color("Red Dark", bundle: .current)
    /// Orbit Red Dark Active color.
    static let redDarkActive = Color("Red Dark Active", bundle: .current)
    /// Orbit Red Dark Hover color.
    static let redDarkHover = Color("Red Dark Hover", bundle: .current)
    /// Orbit Red Darker color.
    static let redDarker = Color("Red Darker", bundle: .current)
    /// Orbit Red Light color.
    static let redLight = Color("Red Light", bundle: .current)
    /// Orbit Red Light Active color.
    static let redLightActive = Color("Red Light Active", bundle: .current)
    /// Orbit Red Light Hover color.
    static let redLightHover = Color("Red Light Hover", bundle: .current)
    /// Orbit Red Normal color.
    static let redNormal = Color("Red Normal", bundle: .current)
    /// Orbit Red Normal Active color.
    static let redNormalActive = Color("Red Normal Active", bundle: .current)
    /// Orbit Red Normal Hover color.
    static let redNormalHover = Color("Red Normal Hover", bundle: .current)

    // MARK: - Social
    /// Orbit Social Facebook color.
    static let socialFacebook = Color("Social Facebook", bundle: .current)
    /// Orbit Social Facebook Active color.
    static let socialFacebookActive = Color("Social Facebook Active", bundle: .current)
    /// Orbit Social Facebook Hover color.
    static let socialFacebookHover = Color("Social Facebook Hover", bundle: .current)

    // MARK: - White
    /// Orbit White color.
    static let whiteNormal = Color("White", bundle: .current)
    /// Orbit White Active color.
    static let whiteActive = Color("White Active", bundle: .current)
    /// Orbit White Hover color.
    static let whiteHover = Color("White Hover", bundle: .current)
}
