import SwiftUI

// Generated by 'Automation/update_colors.py'
public extension Color {

    // MARK: - Blue
    /// Orbit Blue Dark color.
    static var blueDark = Color("Blue Dark", bundle: .current)
    /// Orbit Blue Dark Active color.
    static var blueDarkActive = Color("Blue Dark Active", bundle: .current)
    /// Orbit Blue Dark Hover color.
    static var blueDarkHover = Color("Blue Dark Hover", bundle: .current)
    /// Orbit Blue Darker color.
    static var blueDarker = Color("Blue Darker", bundle: .current)
    /// Orbit Blue Light color.
    static var blueLight = Color("Blue Light", bundle: .current)
    /// Orbit Blue Light Active color.
    static var blueLightActive = Color("Blue Light Active", bundle: .current)
    /// Orbit Blue Light Hover color.
    static var blueLightHover = Color("Blue Light Hover", bundle: .current)
    /// Orbit Blue Normal color.
    static var blueNormal = Color("Blue Normal", bundle: .current)
    /// Orbit Blue Normal Active color.
    static var blueNormalActive = Color("Blue Normal Active", bundle: .current)
    /// Orbit Blue Normal Hover color.
    static var blueNormalHover = Color("Blue Normal Hover", bundle: .current)

    // MARK: - Bundle
    /// Orbit Bundle Basic color.
    static var bundleBasic = Color("Bundle Basic", bundle: .current)
    /// Orbit Bundle Medium color.
    static var bundleMedium = Color("Bundle Medium", bundle: .current)

    // MARK: - Cloud
    /// Orbit Cloud Dark color.
    static var cloudDark = Color("Cloud Dark", bundle: .current)
    /// Orbit Cloud Darker color.
    static var cloudDarker = Color("Cloud Darker", bundle: .current)
    /// Orbit Cloud Darker Active color.
    static var cloudDarkerActive = Color("Cloud Darker Active", bundle: .current)
    /// Orbit Cloud Darker Hover color.
    static var cloudDarkerHover = Color("Cloud Darker Hover", bundle: .current)
    /// Orbit Cloud Light color.
    static var cloudLight = Color("Cloud Light", bundle: .current)
    /// Orbit Cloud Light Active color.
    static var cloudLightActive = Color("Cloud Light Active", bundle: .current)
    /// Orbit Cloud Light Hover color.
    static var cloudLightHover = Color("Cloud Light Hover", bundle: .current)
    /// Orbit Cloud Normal color.
    static var cloudNormal = Color("Cloud Normal", bundle: .current)
    /// Orbit Cloud Normal Active color.
    static var cloudNormalActive = Color("Cloud Normal Active", bundle: .current)
    /// Orbit Cloud Normal Hover color.
    static var cloudNormalHover = Color("Cloud Normal Hover", bundle: .current)

    // MARK: - Green
    /// Orbit Green Dark color.
    static var greenDark = Color("Green Dark", bundle: .current)
    /// Orbit Green Dark Active color.
    static var greenDarkActive = Color("Green Dark Active", bundle: .current)
    /// Orbit Green Dark Hover color.
    static var greenDarkHover = Color("Green Dark Hover", bundle: .current)
    /// Orbit Green Darker color.
    static var greenDarker = Color("Green Darker", bundle: .current)
    /// Orbit Green Light color.
    static var greenLight = Color("Green Light", bundle: .current)
    /// Orbit Green Light Active color.
    static var greenLightActive = Color("Green Light Active", bundle: .current)
    /// Orbit Green Light Hover color.
    static var greenLightHover = Color("Green Light Hover", bundle: .current)
    /// Orbit Green Normal color.
    static var greenNormal = Color("Green Normal", bundle: .current)
    /// Orbit Green Normal Active color.
    static var greenNormalActive = Color("Green Normal Active", bundle: .current)
    /// Orbit Green Normal Hover color.
    static var greenNormalHover = Color("Green Normal Hover", bundle: .current)

    // MARK: - Ink
    /// Orbit Ink Light color.
    static var inkLight = Color("Ink Light", bundle: .current)
    /// Orbit Ink Light Active color.
    static var inkLightActive = Color("Ink Light Active", bundle: .current)
    /// Orbit Ink Light Hover color.
    static var inkLightHover = Color("Ink Light Hover", bundle: .current)
    /// Orbit Ink Lighter color.
    static var inkLighter = Color("Ink Lighter", bundle: .current)
    /// Orbit Ink Lighter Active color.
    static var inkLighterActive = Color("Ink Lighter Active", bundle: .current)
    /// Orbit Ink Lighter Hover color.
    static var inkLighterHover = Color("Ink Lighter Hover", bundle: .current)
    /// Orbit Ink Normal color.
    static var inkNormal = Color("Ink Normal", bundle: .current)
    /// Orbit Ink Normal Active color.
    static var inkNormalActive = Color("Ink Normal Active", bundle: .current)
    /// Orbit Ink Normal Hover color.
    static var inkNormalHover = Color("Ink Normal Hover", bundle: .current)

    // MARK: - Orange
    /// Orbit Orange Dark color.
    static var orangeDark = Color("Orange Dark", bundle: .current)
    /// Orbit Orange Dark Active color.
    static var orangeDarkActive = Color("Orange Dark Active", bundle: .current)
    /// Orbit Orange Dark Hover color.
    static var orangeDarkHover = Color("Orange Dark Hover", bundle: .current)
    /// Orbit Orange Darker color.
    static var orangeDarker = Color("Orange Darker", bundle: .current)
    /// Orbit Orange Light color.
    static var orangeLight = Color("Orange Light", bundle: .current)
    /// Orbit Orange Light Active color.
    static var orangeLightActive = Color("Orange Light Active", bundle: .current)
    /// Orbit Orange Light Hover color.
    static var orangeLightHover = Color("Orange Light Hover", bundle: .current)
    /// Orbit Orange Normal color.
    static var orangeNormal = Color("Orange Normal", bundle: .current)
    /// Orbit Orange Normal Active color.
    static var orangeNormalActive = Color("Orange Normal Active", bundle: .current)
    /// Orbit Orange Normal Hover color.
    static var orangeNormalHover = Color("Orange Normal Hover", bundle: .current)

    // MARK: - Product
    /// Orbit Product Dark color.
    static var productDark = Color("Product Dark", bundle: .current)
    /// Orbit Product Dark Active color.
    static var productDarkActive = Color("Product Dark Active", bundle: .current)
    /// Orbit Product Dark Hover color.
    static var productDarkHover = Color("Product Dark Hover", bundle: .current)
    /// Orbit Product Darker color.
    static var productDarker = Color("Product Darker", bundle: .current)
    /// Orbit Product Light color.
    static var productLight = Color("Product Light", bundle: .current)
    /// Orbit Product Light Active color.
    static var productLightActive = Color("Product Light Active", bundle: .current)
    /// Orbit Product Light Hover color.
    static var productLightHover = Color("Product Light Hover", bundle: .current)
    /// Orbit Product Normal color.
    static var productNormal = Color("Product Normal", bundle: .current)
    /// Orbit Product Normal Active color.
    static var productNormalActive = Color("Product Normal Active", bundle: .current)
    /// Orbit Product Normal Hover color.
    static var productNormalHover = Color("Product Normal Hover", bundle: .current)

    // MARK: - Red
    /// Orbit Red Dark color.
    static var redDark = Color("Red Dark", bundle: .current)
    /// Orbit Red Dark Active color.
    static var redDarkActive = Color("Red Dark Active", bundle: .current)
    /// Orbit Red Dark Hover color.
    static var redDarkHover = Color("Red Dark Hover", bundle: .current)
    /// Orbit Red Darker color.
    static var redDarker = Color("Red Darker", bundle: .current)
    /// Orbit Red Light color.
    static var redLight = Color("Red Light", bundle: .current)
    /// Orbit Red Light Active color.
    static var redLightActive = Color("Red Light Active", bundle: .current)
    /// Orbit Red Light Hover color.
    static var redLightHover = Color("Red Light Hover", bundle: .current)
    /// Orbit Red Normal color.
    static var redNormal = Color("Red Normal", bundle: .current)
    /// Orbit Red Normal Active color.
    static var redNormalActive = Color("Red Normal Active", bundle: .current)
    /// Orbit Red Normal Hover color.
    static var redNormalHover = Color("Red Normal Hover", bundle: .current)

    // MARK: - Social
    /// Orbit Social Facebook color.
    static var socialFacebook = Color("Social Facebook", bundle: .current)
    /// Orbit Social Facebook Active color.
    static var socialFacebookActive = Color("Social Facebook Active", bundle: .current)
    /// Orbit Social Facebook Hover color.
    static var socialFacebookHover = Color("Social Facebook Hover", bundle: .current)

    // MARK: - White
    /// Orbit White color.
    static var whiteNormal = Color("White", bundle: .current)
    /// Orbit White Active color.
    static var whiteActive = Color("White Active", bundle: .current)
    /// Orbit White Darker color.
    static var whiteDarker = Color("White Darker", bundle: .current)
    /// Orbit White Hover color.
    static var whiteHover = Color("White Hover", bundle: .current)
    /// Orbit White Lighter color.
    static var whiteLighter = Color("White Lighter", bundle: .current)
}
