import SwiftUI

// Generated by 'Automation/update_colors.py'

public extension ShapeStyle where Self == Color {

    // MARK: - Blue
    /// Orbit Blue Dark shape style.
    static var blueDark: Self { .blueDark }
    /// Orbit Blue Dark Active shape style.
    static var blueDarkActive: Self { .blueDarkActive }
    /// Orbit Blue Dark Hover shape style.
    static var blueDarkHover: Self { .blueDarkHover }
    /// Orbit Blue Darker shape style.
    static var blueDarker: Self { .blueDarker }
    /// Orbit Blue Light shape style.
    static var blueLight: Self { .blueLight }
    /// Orbit Blue Light Active shape style.
    static var blueLightActive: Self { .blueLightActive }
    /// Orbit Blue Light Hover shape style.
    static var blueLightHover: Self { .blueLightHover }
    /// Orbit Blue Normal shape style.
    static var blueNormal: Self { .blueNormal }
    /// Orbit Blue Normal Active shape style.
    static var blueNormalActive: Self { .blueNormalActive }
    /// Orbit Blue Normal Hover shape style.
    static var blueNormalHover: Self { .blueNormalHover }

    // MARK: - Bundle
    /// Orbit Bundle Basic shape style.
    static var bundleBasic: Self { .bundleBasic }
    /// Orbit Bundle Medium shape style.
    static var bundleMedium: Self { .bundleMedium }

    // MARK: - Cloud
    /// Orbit Cloud Dark shape style.
    static var cloudDark: Self { .cloudDark }
    /// Orbit Cloud Dark Active shape style.
    static var cloudDarkActive: Self { .cloudDarkActive }
    /// Orbit Cloud Dark Hover shape style.
    static var cloudDarkHover: Self { .cloudDarkHover }
    /// Orbit Cloud Light shape style.
    static var cloudLight: Self { .cloudLight }
    /// Orbit Cloud Light Active shape style.
    static var cloudLightActive: Self { .cloudLightActive }
    /// Orbit Cloud Light Hover shape style.
    static var cloudLightHover: Self { .cloudLightHover }
    /// Orbit Cloud Normal shape style.
    static var cloudNormal: Self { .cloudNormal }
    /// Orbit Cloud Normal Active shape style.
    static var cloudNormalActive: Self { .cloudNormalActive }
    /// Orbit Cloud Normal Hover shape style.
    static var cloudNormalHover: Self { .cloudNormalHover }

    // MARK: - Green
    /// Orbit Green Dark shape style.
    static var greenDark: Self { .greenDark }
    /// Orbit Green Dark Active shape style.
    static var greenDarkActive: Self { .greenDarkActive }
    /// Orbit Green Dark Hover shape style.
    static var greenDarkHover: Self { .greenDarkHover }
    /// Orbit Green Darker shape style.
    static var greenDarker: Self { .greenDarker }
    /// Orbit Green Light shape style.
    static var greenLight: Self { .greenLight }
    /// Orbit Green Light Active shape style.
    static var greenLightActive: Self { .greenLightActive }
    /// Orbit Green Light Hover shape style.
    static var greenLightHover: Self { .greenLightHover }
    /// Orbit Green Normal shape style.
    static var greenNormal: Self { .greenNormal }
    /// Orbit Green Normal Active shape style.
    static var greenNormalActive: Self { .greenNormalActive }
    /// Orbit Green Normal Hover shape style.
    static var greenNormalHover: Self { .greenNormalHover }

    // MARK: - Ink
    /// Orbit Ink Dark shape style.
    static var inkDark: Self { .inkDark }
    /// Orbit Ink Dark Active shape style.
    static var inkDarkActive: Self { .inkDarkActive }
    /// Orbit Ink Dark Hover shape style.
    static var inkDarkHover: Self { .inkDarkHover }
    /// Orbit Ink Light shape style.
    static var inkLight: Self { .inkLight }
    /// Orbit Ink Light Active shape style.
    static var inkLightActive: Self { .inkLightActive }
    /// Orbit Ink Light Hover shape style.
    static var inkLightHover: Self { .inkLightHover }
    /// Orbit Ink Normal shape style.
    static var inkNormal: Self { .inkNormal }
    /// Orbit Ink Normal Active shape style.
    static var inkNormalActive: Self { .inkNormalActive }
    /// Orbit Ink Normal Hover shape style.
    static var inkNormalHover: Self { .inkNormalHover }

    // MARK: - Orange
    /// Orbit Orange Dark shape style.
    static var orangeDark: Self { .orangeDark }
    /// Orbit Orange Dark Active shape style.
    static var orangeDarkActive: Self { .orangeDarkActive }
    /// Orbit Orange Dark Hover shape style.
    static var orangeDarkHover: Self { .orangeDarkHover }
    /// Orbit Orange Darker shape style.
    static var orangeDarker: Self { .orangeDarker }
    /// Orbit Orange Light shape style.
    static var orangeLight: Self { .orangeLight }
    /// Orbit Orange Light Active shape style.
    static var orangeLightActive: Self { .orangeLightActive }
    /// Orbit Orange Light Hover shape style.
    static var orangeLightHover: Self { .orangeLightHover }
    /// Orbit Orange Normal shape style.
    static var orangeNormal: Self { .orangeNormal }
    /// Orbit Orange Normal Active shape style.
    static var orangeNormalActive: Self { .orangeNormalActive }
    /// Orbit Orange Normal Hover shape style.
    static var orangeNormalHover: Self { .orangeNormalHover }

    // MARK: - Product
    /// Orbit Product Dark shape style.
    static var productDark: Self { .productDark }
    /// Orbit Product Dark Active shape style.
    static var productDarkActive: Self { .productDarkActive }
    /// Orbit Product Dark Hover shape style.
    static var productDarkHover: Self { .productDarkHover }
    /// Orbit Product Darker shape style.
    static var productDarker: Self { .productDarker }
    /// Orbit Product Light shape style.
    static var productLight: Self { .productLight }
    /// Orbit Product Light Active shape style.
    static var productLightActive: Self { .productLightActive }
    /// Orbit Product Light Hover shape style.
    static var productLightHover: Self { .productLightHover }
    /// Orbit Product Normal shape style.
    static var productNormal: Self { .productNormal }
    /// Orbit Product Normal Active shape style.
    static var productNormalActive: Self { .productNormalActive }
    /// Orbit Product Normal Hover shape style.
    static var productNormalHover: Self { .productNormalHover }

    // MARK: - Red
    /// Orbit Red Dark shape style.
    static var redDark: Self { .redDark }
    /// Orbit Red Dark Active shape style.
    static var redDarkActive: Self { .redDarkActive }
    /// Orbit Red Dark Hover shape style.
    static var redDarkHover: Self { .redDarkHover }
    /// Orbit Red Darker shape style.
    static var redDarker: Self { .redDarker }
    /// Orbit Red Light shape style.
    static var redLight: Self { .redLight }
    /// Orbit Red Light Active shape style.
    static var redLightActive: Self { .redLightActive }
    /// Orbit Red Light Hover shape style.
    static var redLightHover: Self { .redLightHover }
    /// Orbit Red Normal shape style.
    static var redNormal: Self { .redNormal }
    /// Orbit Red Normal Active shape style.
    static var redNormalActive: Self { .redNormalActive }
    /// Orbit Red Normal Hover shape style.
    static var redNormalHover: Self { .redNormalHover }

    // MARK: - Social
    /// Orbit Social Facebook shape style.
    static var socialFacebook: Self { .socialFacebook }
    /// Orbit Social Facebook Active shape style.
    static var socialFacebookActive: Self { .socialFacebookActive }
    /// Orbit Social Facebook Hover shape style.
    static var socialFacebookHover: Self { .socialFacebookHover }

    // MARK: - White
    /// Orbit White Active shape style.
    static var whiteActive: Self { .whiteActive }
    /// Orbit White Darker shape style.
    static var whiteDarker: Self { .whiteDarker }
    /// Orbit White Hover shape style.
    static var whiteHover: Self { .whiteHover }
    /// Orbit White Lighter shape style.
    static var whiteLighter: Self { .whiteLighter }
    /// Orbit White Normal shape style.
    static var whiteNormal: Self { .whiteNormal }
}
