import UIKit

// Generated by 'Automation/update_colors.py'
public extension UIColor {

    // MARK: - Blue
    /// Orbit Blue Dark color.
    static var blueDark = fromResource(named: "Blue Dark")
    /// Orbit Blue Dark Active color.
    static var blueDarkActive = fromResource(named: "Blue Dark Active")
    /// Orbit Blue Dark Hover color.
    static var blueDarkHover = fromResource(named: "Blue Dark Hover")
    /// Orbit Blue Darker color.
    static var blueDarker = fromResource(named: "Blue Darker")
    /// Orbit Blue Light color.
    static var blueLight = fromResource(named: "Blue Light")
    /// Orbit Blue Light Active color.
    static var blueLightActive = fromResource(named: "Blue Light Active")
    /// Orbit Blue Light Hover color.
    static var blueLightHover = fromResource(named: "Blue Light Hover")
    /// Orbit Blue Normal color.
    static var blueNormal = fromResource(named: "Blue Normal")
    /// Orbit Blue Normal Active color.
    static var blueNormalActive = fromResource(named: "Blue Normal Active")
    /// Orbit Blue Normal Hover color.
    static var blueNormalHover = fromResource(named: "Blue Normal Hover")

    // MARK: - Bundle
    /// Orbit Bundle Basic color.
    static var bundleBasic = fromResource(named: "Bundle Basic")
    /// Orbit Bundle Medium color.
    static var bundleMedium = fromResource(named: "Bundle Medium")

    // MARK: - Cloud
    /// Orbit Cloud Dark color.
    static var cloudDark = fromResource(named: "Cloud Dark")
    /// Orbit Cloud Darker color.
    static var cloudDarker = fromResource(named: "Cloud Darker")
    /// Orbit Cloud Darker Active color.
    static var cloudDarkerActive = fromResource(named: "Cloud Darker Active")
    /// Orbit Cloud Darker Hover color.
    static var cloudDarkerHover = fromResource(named: "Cloud Darker Hover")
    /// Orbit Cloud Light color.
    static var cloudLight = fromResource(named: "Cloud Light")
    /// Orbit Cloud Light Active color.
    static var cloudLightActive = fromResource(named: "Cloud Light Active")
    /// Orbit Cloud Light Hover color.
    static var cloudLightHover = fromResource(named: "Cloud Light Hover")
    /// Orbit Cloud Normal color.
    static var cloudNormal = fromResource(named: "Cloud Normal")
    /// Orbit Cloud Normal Active color.
    static var cloudNormalActive = fromResource(named: "Cloud Normal Active")
    /// Orbit Cloud Normal Hover color.
    static var cloudNormalHover = fromResource(named: "Cloud Normal Hover")

    // MARK: - Green
    /// Orbit Green Dark color.
    static var greenDark = fromResource(named: "Green Dark")
    /// Orbit Green Dark Active color.
    static var greenDarkActive = fromResource(named: "Green Dark Active")
    /// Orbit Green Dark Hover color.
    static var greenDarkHover = fromResource(named: "Green Dark Hover")
    /// Orbit Green Darker color.
    static var greenDarker = fromResource(named: "Green Darker")
    /// Orbit Green Light color.
    static var greenLight = fromResource(named: "Green Light")
    /// Orbit Green Light Active color.
    static var greenLightActive = fromResource(named: "Green Light Active")
    /// Orbit Green Light Hover color.
    static var greenLightHover = fromResource(named: "Green Light Hover")
    /// Orbit Green Normal color.
    static var greenNormal = fromResource(named: "Green Normal")
    /// Orbit Green Normal Active color.
    static var greenNormalActive = fromResource(named: "Green Normal Active")
    /// Orbit Green Normal Hover color.
    static var greenNormalHover = fromResource(named: "Green Normal Hover")

    // MARK: - Ink
    /// Orbit Ink Light color.
    static var inkLight = fromResource(named: "Ink Light")
    /// Orbit Ink Light Active color.
    static var inkLightActive = fromResource(named: "Ink Light Active")
    /// Orbit Ink Light Hover color.
    static var inkLightHover = fromResource(named: "Ink Light Hover")
    /// Orbit Ink Lighter color.
    static var inkLighter = fromResource(named: "Ink Lighter")
    /// Orbit Ink Lighter Active color.
    static var inkLighterActive = fromResource(named: "Ink Lighter Active")
    /// Orbit Ink Lighter Hover color.
    static var inkLighterHover = fromResource(named: "Ink Lighter Hover")
    /// Orbit Ink Normal color.
    static var inkNormal = fromResource(named: "Ink Normal")
    /// Orbit Ink Normal Active color.
    static var inkNormalActive = fromResource(named: "Ink Normal Active")
    /// Orbit Ink Normal Hover color.
    static var inkNormalHover = fromResource(named: "Ink Normal Hover")

    // MARK: - Orange
    /// Orbit Orange Dark color.
    static var orangeDark = fromResource(named: "Orange Dark")
    /// Orbit Orange Dark Active color.
    static var orangeDarkActive = fromResource(named: "Orange Dark Active")
    /// Orbit Orange Dark Hover color.
    static var orangeDarkHover = fromResource(named: "Orange Dark Hover")
    /// Orbit Orange Darker color.
    static var orangeDarker = fromResource(named: "Orange Darker")
    /// Orbit Orange Light color.
    static var orangeLight = fromResource(named: "Orange Light")
    /// Orbit Orange Light Active color.
    static var orangeLightActive = fromResource(named: "Orange Light Active")
    /// Orbit Orange Light Hover color.
    static var orangeLightHover = fromResource(named: "Orange Light Hover")
    /// Orbit Orange Normal color.
    static var orangeNormal = fromResource(named: "Orange Normal")
    /// Orbit Orange Normal Active color.
    static var orangeNormalActive = fromResource(named: "Orange Normal Active")
    /// Orbit Orange Normal Hover color.
    static var orangeNormalHover = fromResource(named: "Orange Normal Hover")

    // MARK: - Product
    /// Orbit Product Dark color.
    static var productDark = fromResource(named: "Product Dark")
    /// Orbit Product Dark Active color.
    static var productDarkActive = fromResource(named: "Product Dark Active")
    /// Orbit Product Dark Hover color.
    static var productDarkHover = fromResource(named: "Product Dark Hover")
    /// Orbit Product Darker color.
    static var productDarker = fromResource(named: "Product Darker")
    /// Orbit Product Light color.
    static var productLight = fromResource(named: "Product Light")
    /// Orbit Product Light Active color.
    static var productLightActive = fromResource(named: "Product Light Active")
    /// Orbit Product Light Hover color.
    static var productLightHover = fromResource(named: "Product Light Hover")
    /// Orbit Product Normal color.
    static var productNormal = fromResource(named: "Product Normal")
    /// Orbit Product Normal Active color.
    static var productNormalActive = fromResource(named: "Product Normal Active")
    /// Orbit Product Normal Hover color.
    static var productNormalHover = fromResource(named: "Product Normal Hover")

    // MARK: - Red
    /// Orbit Red Dark color.
    static var redDark = fromResource(named: "Red Dark")
    /// Orbit Red Dark Active color.
    static var redDarkActive = fromResource(named: "Red Dark Active")
    /// Orbit Red Dark Hover color.
    static var redDarkHover = fromResource(named: "Red Dark Hover")
    /// Orbit Red Darker color.
    static var redDarker = fromResource(named: "Red Darker")
    /// Orbit Red Light color.
    static var redLight = fromResource(named: "Red Light")
    /// Orbit Red Light Active color.
    static var redLightActive = fromResource(named: "Red Light Active")
    /// Orbit Red Light Hover color.
    static var redLightHover = fromResource(named: "Red Light Hover")
    /// Orbit Red Normal color.
    static var redNormal = fromResource(named: "Red Normal")
    /// Orbit Red Normal Active color.
    static var redNormalActive = fromResource(named: "Red Normal Active")
    /// Orbit Red Normal Hover color.
    static var redNormalHover = fromResource(named: "Red Normal Hover")

    // MARK: - Social
    /// Orbit Social Facebook color.
    static var socialFacebook = fromResource(named: "Social Facebook")
    /// Orbit Social Facebook Active color.
    static var socialFacebookActive = fromResource(named: "Social Facebook Active")
    /// Orbit Social Facebook Hover color.
    static var socialFacebookHover = fromResource(named: "Social Facebook Hover")

    // MARK: - White
    /// Orbit White color.
    static var whiteNormal = fromResource(named: "White")
    /// Orbit White Active color.
    static var whiteActive = fromResource(named: "White Active")
    /// Orbit White Darker color.
    static var whiteDarker = fromResource(named: "White Darker")
    /// Orbit White Hover color.
    static var whiteHover = fromResource(named: "White Hover")
    /// Orbit White Lighter color.
    static var whiteLighter = fromResource(named: "White Lighter")
}
