
// Generated by 'Automation/update_icons.py'
public extension Icon {

    enum Symbol: CaseIterable {
        /// Absence of Orbit icon.
        case none
        /// Orbit `accommodation` icon symbol.
        case accommodation
        /// Orbit `accountCircle` icon symbol.
        case accountCircle
        /// Orbit `admin` icon symbol.
        case admin
        /// Orbit `ai` icon symbol.
        case ai
        /// Orbit `airConditioning` icon symbol.
        case airConditioning
        /// Orbit `airplane` icon symbol.
        case airplane
        /// Orbit `airplaneDown` icon symbol.
        case airplaneDown
        /// Orbit `airplaneLanding` icon symbol.
        case airplaneLanding
        /// Orbit `airplaneReturn` icon symbol.
        case airplaneReturn
        /// Orbit `airplaneTakeoff` icon symbol.
        case airplaneTakeoff
        /// Orbit `airplaneUp` icon symbol.
        case airplaneUp
        /// Orbit `airplaneUpOff` icon symbol.
        case airplaneUpOff
        /// Orbit `airportSecurity` icon symbol.
        case airportSecurity
        /// Orbit `alert` icon symbol.
        case alert
        /// Orbit `alertCircle` icon symbol.
        case alertCircle
        /// Orbit `alertOctagon` icon symbol.
        case alertOctagon
        /// Orbit `all` icon symbol.
        case all
        /// Orbit `android` icon symbol.
        case android
        /// Orbit `anywhere` icon symbol.
        case anywhere
        /// Orbit `apple` icon symbol.
        case apple
        /// Orbit `arrowDown` icon symbol.
        case arrowDown
        /// Orbit `arrowUp` icon symbol.
        case arrowUp
        /// Orbit `atm` icon symbol.
        case atm
        /// Orbit `attachment` icon symbol.
        case attachment
        /// Orbit `baggageCabin` icon symbol.
        case baggageCabin
        /// Orbit `baggageCabinNone` icon symbol.
        case baggageCabinNone
        /// Orbit `baggageChecked10` icon symbol.
        case baggageChecked10
        /// Orbit `baggageChecked20` icon symbol.
        case baggageChecked20
        /// Orbit `baggageChecked30` icon symbol.
        case baggageChecked30
        /// Orbit `baggageCheckedNone` icon symbol.
        case baggageCheckedNone
        /// Orbit `baggagePersonal` icon symbol.
        case baggagePersonal
        /// Orbit `baggagePersonalNone` icon symbol.
        case baggagePersonalNone
        /// Orbit `baggageRecheck` icon symbol.
        case baggageRecheck
        /// Orbit `baggageSet` icon symbol.
        case baggageSet
        /// Orbit `baggageStorage` icon symbol.
        case baggageStorage
        /// Orbit `billingDetails` icon symbol.
        case billingDetails
        /// Orbit `boardingGate` icon symbol.
        case boardingGate
        /// Orbit `boat` icon symbol.
        case boat
        /// Orbit `bug` icon symbol.
        case bug
        /// Orbit `bus` icon symbol.
        case bus
        /// Orbit `cake` icon symbol.
        case cake
        /// Orbit `calendar` icon symbol.
        case calendar
        /// Orbit `calendarAnytime` icon symbol.
        case calendarAnytime
        /// Orbit `calendarRange` icon symbol.
        case calendarRange
        /// Orbit `calendarTripLength` icon symbol.
        case calendarTripLength
        /// Orbit `camera` icon symbol.
        case camera
        /// Orbit `car` icon symbol.
        case car
        /// Orbit `carDoor` icon symbol.
        case carDoor
        /// Orbit `carRental` icon symbol.
        case carRental
        /// Orbit `chart` icon symbol.
        case chart
        /// Orbit `chat` icon symbol.
        case chat
        /// Orbit `check` icon symbol.
        case check
        /// Orbit `checkCircle` icon symbol.
        case checkCircle
        /// Orbit `chevronDoubleLeft` icon symbol.
        case chevronDoubleLeft
        /// Orbit `chevronDoubleRight` icon symbol.
        case chevronDoubleRight
        /// Orbit `chevronDown` icon symbol.
        case chevronDown
        /// Orbit `chevronLeft` icon symbol.
        case chevronLeft
        /// Orbit `chevronRight` icon symbol.
        case chevronRight
        /// Orbit `chevronUp` icon symbol.
        case chevronUp
        /// Orbit `child` icon symbol.
        case child
        /// Orbit `childFriendly` icon symbol.
        case childFriendly
        /// Orbit `circle` icon symbol.
        case circle
        /// Orbit `circleEmpty` icon symbol.
        case circleEmpty
        /// Orbit `circleFilled` icon symbol.
        case circleFilled
        /// Orbit `circleSmall` icon symbol.
        case circleSmall
        /// Orbit `city` icon symbol.
        case city
        /// Orbit `clock` icon symbol.
        case clock
        /// Orbit `close` icon symbol.
        case close
        /// Orbit `closeCircle` icon symbol.
        case closeCircle
        /// Orbit `cocktail` icon symbol.
        case cocktail
        /// Orbit `code` icon symbol.
        case code
        /// Orbit `coffee` icon symbol.
        case coffee
        /// Orbit `colorPicker` icon symbol.
        case colorPicker
        /// Orbit `coloredFacebook` icon symbol.
        case coloredFacebook
        /// Orbit `coloredImessage` icon symbol.
        case coloredImessage
        /// Orbit `coloredMessenger` icon symbol.
        case coloredMessenger
        /// Orbit `coloredTwitter` icon symbol.
        case coloredTwitter
        /// Orbit `coloredWhatsapp` icon symbol.
        case coloredWhatsapp
        /// Orbit `compare` icon symbol.
        case compare
        /// Orbit `compass` icon symbol.
        case compass
        /// Orbit `contactEmail` icon symbol.
        case contactEmail
        /// Orbit `creditCard` icon symbol.
        case creditCard
        /// Orbit `customerSupport` icon symbol.
        case customerSupport
        /// Orbit `dashboard` icon symbol.
        case dashboard
        /// Orbit `deals` icon symbol.
        case deals
        /// Orbit `dealsV2` icon symbol.
        case dealsV2
        /// Orbit `deviceDesktop` icon symbol.
        case deviceDesktop
        /// Orbit `deviceMobile` icon symbol.
        case deviceMobile
        /// Orbit `diamond` icon symbol.
        case diamond
        /// Orbit `document` icon symbol.
        case document
        /// Orbit `download` icon symbol.
        case download
        /// Orbit `duplicate` icon symbol.
        case duplicate
        /// Orbit `edit` icon symbol.
        case edit
        /// Orbit `editOff` icon symbol.
        case editOff
        /// Orbit `email` icon symbol.
        case email
        /// Orbit `entertainment` icon symbol.
        case entertainment
        /// Orbit `exchange` icon symbol.
        case exchange
        /// Orbit `facebook` icon symbol.
        case facebook
        /// Orbit `feedback` icon symbol.
        case feedback
        /// Orbit `filters` icon symbol.
        case filters
        /// Orbit `flash` icon symbol.
        case flash
        /// Orbit `flightDirect` icon symbol.
        case flightDirect
        /// Orbit `flightMulticity` icon symbol.
        case flightMulticity
        /// Orbit `flightNomad` icon symbol.
        case flightNomad
        /// Orbit `flightReturn` icon symbol.
        case flightReturn
        /// Orbit `flightServices` icon symbol.
        case flightServices
        /// Orbit `fuel` icon symbol.
        case fuel
        /// Orbit `fullScreen` icon symbol.
        case fullScreen
        /// Orbit `fullScreenOff` icon symbol.
        case fullScreenOff
        /// Orbit `gallery` icon symbol.
        case gallery
        /// Orbit `genderMan` icon symbol.
        case genderMan
        /// Orbit `genderWoman` icon symbol.
        case genderWoman
        /// Orbit `google` icon symbol.
        case google
        /// Orbit `gpsFixed` icon symbol.
        case gpsFixed
        /// Orbit `gpsIos` icon symbol.
        case gpsIos
        /// Orbit `gpsNotFixed` icon symbol.
        case gpsNotFixed
        /// Orbit `gpsOff` icon symbol.
        case gpsOff
        /// Orbit `grid` icon symbol.
        case grid
        /// Orbit `gym` icon symbol.
        case gym
        /// Orbit `history` icon symbol.
        case history
        /// Orbit `infant` icon symbol.
        case infant
        /// Orbit `informationCircle` icon symbol.
        case informationCircle
        /// Orbit `instagram` icon symbol.
        case instagram
        /// Orbit `insurance` icon symbol.
        case insurance
        /// Orbit `insuranceConfirmed` icon symbol.
        case insuranceConfirmed
        /// Orbit `insuranceOff` icon symbol.
        case insuranceOff
        /// Orbit `invoice` icon symbol.
        case invoice
        /// Orbit `itemCompleted` icon symbol.
        case itemCompleted
        /// Orbit `kiwicom` icon symbol.
        case kiwicom
        /// Orbit `kiwicomCare` icon symbol.
        case kiwicomCare
        /// Orbit `kiwicomGuarantee` icon symbol.
        case kiwicomGuarantee
        /// Orbit `leisure` icon symbol.
        case leisure
        /// Orbit `link` icon symbol.
        case link
        /// Orbit `linkedin` icon symbol.
        case linkedin
        /// Orbit `list` icon symbol.
        case list
        /// Orbit `location` icon symbol.
        case location
        /// Orbit `locationA` icon symbol.
        case locationA
        /// Orbit `locationAdd` icon symbol.
        case locationAdd
        /// Orbit `locationB` icon symbol.
        case locationB
        /// Orbit `locationC` icon symbol.
        case locationC
        /// Orbit `locationD` icon symbol.
        case locationD
        /// Orbit `locationE` icon symbol.
        case locationE
        /// Orbit `locationF` icon symbol.
        case locationF
        /// Orbit `locationG` icon symbol.
        case locationG
        /// Orbit `locationH` icon symbol.
        case locationH
        /// Orbit `locationI` icon symbol.
        case locationI
        /// Orbit `locationJ` icon symbol.
        case locationJ
        /// Orbit `lock` icon symbol.
        case lock
        /// Orbit `lockOpen` icon symbol.
        case lockOpen
        /// Orbit `logout` icon symbol.
        case logout
        /// Orbit `lounge` icon symbol.
        case lounge
        /// Orbit `map` icon symbol.
        case map
        /// Orbit `markdown` icon symbol.
        case markdown
        /// Orbit `meal` icon symbol.
        case meal
        /// Orbit `menuHamburger` icon symbol.
        case menuHamburger
        /// Orbit `menuKebab` icon symbol.
        case menuKebab
        /// Orbit `menuMeatballs` icon symbol.
        case menuMeatballs
        /// Orbit `messages` icon symbol.
        case messages
        /// Orbit `messagesOutline` icon symbol.
        case messagesOutline
        /// Orbit `minus` icon symbol.
        case minus
        /// Orbit `minusCircle` icon symbol.
        case minusCircle
        /// Orbit `money` icon symbol.
        case money
        /// Orbit `moneyTransferIn` icon symbol.
        case moneyTransferIn
        /// Orbit `moneyTransferOut` icon symbol.
        case moneyTransferOut
        /// Orbit `moon` icon symbol.
        case moon
        /// Orbit `musicalInstruments` icon symbol.
        case musicalInstruments
        /// Orbit `newWindow` icon symbol.
        case newWindow
        /// Orbit `noKiwicomGuarantee` icon symbol.
        case noKiwicomGuarantee
        /// Orbit `nonstop` icon symbol.
        case nonstop
        /// Orbit `notification` icon symbol.
        case notification
        /// Orbit `notificationAdd` icon symbol.
        case notificationAdd
        /// Orbit `notificationOff` icon symbol.
        case notificationOff
        /// Orbit `notificationOn` icon symbol.
        case notificationOn
        /// Orbit `onlineCheckin` icon symbol.
        case onlineCheckin
        /// Orbit `onlineCheckinOff` icon symbol.
        case onlineCheckinOff
        /// Orbit `outlook` icon symbol.
        case outlook
        /// Orbit `paid` icon symbol.
        case paid
        /// Orbit `parking` icon symbol.
        case parking
        /// Orbit `partners` icon symbol.
        case partners
        /// Orbit `passenger` icon symbol.
        case passenger
        /// Orbit `passengerAdd` icon symbol.
        case passengerAdd
        /// Orbit `passengerOutline` icon symbol.
        case passengerOutline
        /// Orbit `passengerRemove` icon symbol.
        case passengerRemove
        /// Orbit `passengers` icon symbol.
        case passengers
        /// Orbit `passport` icon symbol.
        case passport
        /// Orbit `pet` icon symbol.
        case pet
        /// Orbit `pharmacy` icon symbol.
        case pharmacy
        /// Orbit `phone` icon symbol.
        case phone
        /// Orbit `playground` icon symbol.
        case playground
        /// Orbit `plus` icon symbol.
        case plus
        /// Orbit `plusCircle` icon symbol.
        case plusCircle
        /// Orbit `pool` icon symbol.
        case pool
        /// Orbit `powerPlug` icon symbol.
        case powerPlug
        /// Orbit `powerPlugOff` icon symbol.
        case powerPlugOff
        /// Orbit `priorityBoarding` icon symbol.
        case priorityBoarding
        /// Orbit `profit` icon symbol.
        case profit
        /// Orbit `promoCode` icon symbol.
        case promoCode
        /// Orbit `qrCode` icon symbol.
        case qrCode
        /// Orbit `questionCircle` icon symbol.
        case questionCircle
        /// Orbit `radar` icon symbol.
        case radar
        /// Orbit `radiusSearch` icon symbol.
        case radiusSearch
        /// Orbit `refund` icon symbol.
        case refund
        /// Orbit `relax` icon symbol.
        case relax
        /// Orbit `reload` icon symbol.
        case reload
        /// Orbit `remove` icon symbol.
        case remove
        /// Orbit `replace` icon symbol.
        case replace
        /// Orbit `restaurant` icon symbol.
        case restaurant
        /// Orbit `routeNoStops` icon symbol.
        case routeNoStops
        /// Orbit `routeOneStop` icon symbol.
        case routeOneStop
        /// Orbit `routeTwoStops` icon symbol.
        case routeTwoStops
        /// Orbit `search` icon symbol.
        case search
        /// Orbit `seat` icon symbol.
        case seat
        /// Orbit `seatAisle` icon symbol.
        case seatAisle
        /// Orbit `seatExtraLegroom` icon symbol.
        case seatExtraLegroom
        /// Orbit `seatWindow` icon symbol.
        case seatWindow
        /// Orbit `security` icon symbol.
        case security
        /// Orbit `selfTransfer` icon symbol.
        case selfTransfer
        /// Orbit `send` icon symbol.
        case send
        /// Orbit `settings` icon symbol.
        case settings
        /// Orbit `share` icon symbol.
        case share
        /// Orbit `shareAndroid` icon symbol.
        case shareAndroid
        /// Orbit `shareIos` icon symbol.
        case shareIos
        /// Orbit `shopping` icon symbol.
        case shopping
        /// Orbit `showLess` icon symbol.
        case showLess
        /// Orbit `showMore` icon symbol.
        case showMore
        /// Orbit `sightseeing` icon symbol.
        case sightseeing
        /// Orbit `smoking` icon symbol.
        case smoking
        /// Orbit `smokingOff` icon symbol.
        case smokingOff
        /// Orbit `sort` icon symbol.
        case sort
        /// Orbit `spa` icon symbol.
        case spa
        /// Orbit `sportEquipment` icon symbol.
        case sportEquipment
        /// Orbit `sports` icon symbol.
        case sports
        /// Orbit `starEmpty` icon symbol.
        case starEmpty
        /// Orbit `starFull` icon symbol.
        case starFull
        /// Orbit `subway` icon symbol.
        case subway
        /// Orbit `suitcase` icon symbol.
        case suitcase
        /// Orbit `sun` icon symbol.
        case sun
        /// Orbit `sunrise` icon symbol.
        case sunrise
        /// Orbit `taxi` icon symbol.
        case taxi
        /// Orbit `terminal` icon symbol.
        case terminal
        /// Orbit `termsAndConditions` icon symbol.
        case termsAndConditions
        /// Orbit `thumbDown` icon symbol.
        case thumbDown
        /// Orbit `thumbUp` icon symbol.
        case thumbUp
        /// Orbit `ticket` icon symbol.
        case ticket
        /// Orbit `ticketOutline` icon symbol.
        case ticketOutline
        /// Orbit `timelapse` icon symbol.
        case timelapse
        /// Orbit `timer` icon symbol.
        case timer
        /// Orbit `tips` icon symbol.
        case tips
        /// Orbit `toilets` icon symbol.
        case toilets
        /// Orbit `train` icon symbol.
        case train
        /// Orbit `transmission` icon symbol.
        case transmission
        /// Orbit `trip` icon symbol.
        case trip
        /// Orbit `twitter` icon symbol.
        case twitter
        /// Orbit `uber` icon symbol.
        case uber
        /// Orbit `upload` icon symbol.
        case upload
        /// Orbit `userGroup` icon symbol.
        case userGroup
        /// Orbit `visa` icon symbol.
        case visa
        /// Orbit `visibility` icon symbol.
        case visibility
        /// Orbit `visibilityOff` icon symbol.
        case visibilityOff
        /// Orbit `walk` icon symbol.
        case walk
        /// Orbit `wallet` icon symbol.
        case wallet
        /// Orbit `wheelchair` icon symbol.
        case wheelchair
        /// Orbit `wifi` icon symbol.
        case wifi
        /// Orbit `wifiOff` icon symbol.
        case wifiOff

        public var value: String {
            switch self {
                case .none: return ""
                case .accommodation: return "\u{e085}"
                case .accountCircle: return "\u{e134}"
                case .admin: return "\u{e253}"
                case .ai: return "\u{e254}"
                case .airConditioning: return "\u{e184}"
                case .airplane: return "\u{0061}"
                case .airplaneDown: return "\u{e101}"
                case .airplaneLanding: return "\u{0025}"
                case .airplaneReturn: return "\u{e159}"
                case .airplaneTakeoff: return "\u{002a}"
                case .airplaneUp: return "\u{e160}"
                case .airplaneUpOff: return "\u{e102}"
                case .airportSecurity: return "\u{e035}"
                case .alert: return "\u{e07f}"
                case .alertCircle: return "\u{0055}"
                case .alertOctagon: return "\u{e207}"
                case .all: return "\u{e061}"
                case .android: return "\u{e255}"
                case .anywhere: return "\u{0067}"
                case .apple: return "\u{e199}"
                case .arrowDown: return "\u{e0a0}"
                case .arrowUp: return "\u{e09f}"
                case .atm: return "\u{e02c}"
                case .attachment: return "\u{e104}"
                case .baggageCabin: return "\u{e106}"
                case .baggageCabinNone: return "\u{e174}"
                case .baggageChecked10: return "\u{e204}"
                case .baggageChecked20: return "\u{e205}"
                case .baggageChecked30: return "\u{0068}"
                case .baggageCheckedNone: return "\u{e021}"
                case .baggagePersonal: return "\u{e156}"
                case .baggagePersonalNone: return "\u{e175}"
                case .baggageRecheck: return "\u{e105}"
                case .baggageSet: return "\u{e107}"
                case .baggageStorage: return "\u{e147}"
                case .billingDetails: return "\u{e108}"
                case .boardingGate: return "\u{e00a}"
                case .boat: return "\u{e139}"
                case .bug: return "\u{004e}"
                case .bus: return "\u{003c}"
                case .cake: return "\u{e187}"
                case .calendar: return "\u{0066}"
                case .calendarAnytime: return "\u{0041}"
                case .calendarRange: return "\u{007a}"
                case .calendarTripLength: return "\u{e109}"
                case .camera: return "\u{e017}"
                case .car: return "\u{e03a}"
                case .carDoor: return "\u{e185}"
                case .carRental: return "\u{e030}"
                case .chart: return "\u{e176}"
                case .chat: return "\u{0039}"
                case .check: return "\u{0056}"
                case .checkCircle: return "\u{0053}"
                case .chevronDoubleLeft: return "\u{e202}"
                case .chevronDoubleRight: return "\u{e203}"
                case .chevronDown: return "\u{e09d}"
                case .chevronLeft: return "\u{0021}"
                case .chevronRight: return "\u{e01f}"
                case .chevronUp: return "\u{006d}"
                case .child: return "\u{e050}"
                case .childFriendly: return "\u{e05d}"
                case .circle: return "\u{e013}"
                case .circleEmpty: return "\u{e179}"
                case .circleFilled: return "\u{e180}"
                case .circleSmall: return "\u{e148}"
                case .city: return "\u{0063}"
                case .clock: return "\u{0065}"
                case .close: return "\u{0058}"
                case .closeCircle: return "\u{0074}"
                case .cocktail: return "\u{e038}"
                case .code: return "\u{e141}"
                case .coffee: return "\u{e02f}"
                case .colorPicker: return "\u{e200}"
                case .coloredFacebook: return "\u{e257}"
                case .coloredImessage: return "\u{e260}"
                case .coloredMessenger: return "\u{e259}"
                case .coloredTwitter: return "\u{e261}"
                case .coloredWhatsapp: return "\u{e262}"
                case .compare: return "\u{e155}"
                case .compass: return "\u{e07e}"
                case .contactEmail: return "\u{0076}"
                case .creditCard: return "\u{0075}"
                case .customerSupport: return "\u{e194}"
                case .dashboard: return "\u{e252}"
                case .deals: return "\u{e142}"
                case .dealsV2: return "\u{e206}"
                case .deviceDesktop: return "\u{e158}"
                case .deviceMobile: return "\u{e157}"
                case .diamond: return "\u{e197}"
                case .document: return "\u{e110}"
                case .download: return "\u{e014}"
                case .duplicate: return "\u{e154}"
                case .edit: return "\u{0045}"
                case .editOff: return "\u{e00d}"
                case .email: return "\u{0047}"
                case .entertainment: return "\u{e06e}"
                case .exchange: return "\u{e032}"
                case .facebook: return "\u{e002}"
                case .feedback: return "\u{e140}"
                case .filters: return "\u{0026}"
                case .flash: return "\u{e220}"
                case .flightDirect: return "\u{0043}"
                case .flightMulticity: return "\u{005d}"
                case .flightNomad: return "\u{e150}"
                case .flightReturn: return "\u{0073}"
                case .flightServices: return "\u{e049}"
                case .fuel: return "\u{e183}"
                case .fullScreen: return "\u{e0a6}"
                case .fullScreenOff: return "\u{e111}"
                case .gallery: return "\u{e064}"
                case .genderMan: return "\u{e152}"
                case .genderWoman: return "\u{e151}"
                case .google: return "\u{e003}"
                case .gpsFixed: return "\u{0022}"
                case .gpsIos: return "\u{e161}"
                case .gpsNotFixed: return "\u{e191}"
                case .gpsOff: return "\u{e01c}"
                case .grid: return "\u{e06d}"
                case .gym: return "\u{e089}"
                case .history: return "\u{e153}"
                case .infant: return "\u{e186}"
                case .informationCircle: return "\u{0052}"
                case .instagram: return "\u{e112}"
                case .insurance: return "\u{0027}"
                case .insuranceConfirmed: return "\u{0072}"
                case .insuranceOff: return "\u{003a}"
                case .invoice: return "\u{e113}"
                case .itemCompleted: return "\u{e149}"
                case .kiwicom: return "\u{e143}"
                case .kiwicomCare: return "\u{e144}"
                case .kiwicomGuarantee: return "\u{e145}"
                case .leisure: return "\u{e178}"
                case .link: return "\u{e057}"
                case .linkedin: return "\u{e114}"
                case .list: return "\u{e115}"
                case .location: return "\u{0024}"
                case .locationA: return "\u{006a}"
                case .locationAdd: return "\u{003f}"
                case .locationB: return "\u{006b}"
                case .locationC: return "\u{005e}"
                case .locationD: return "\u{005f}"
                case .locationE: return "\u{0060}"
                case .locationF: return "\u{007b}"
                case .locationG: return "\u{007c}"
                case .locationH: return "\u{007d}"
                case .locationI: return "\u{007e}"
                case .locationJ: return "\u{005c}"
                case .lock: return "\u{e169}"
                case .lockOpen: return "\u{e170}"
                case .logout: return "\u{e0a7}"
                case .lounge: return "\u{e04e}"
                case .map: return "\u{e001}"
                case .markdown: return "\u{e201}"
                case .meal: return "\u{e116}"
                case .menuHamburger: return "\u{0044}"
                case .menuKebab: return "\u{e117}"
                case .menuMeatballs: return "\u{e07d}"
                case .messages: return "\u{e135}"
                case .messagesOutline: return "\u{e136}"
                case .minus: return "\u{e118}"
                case .minusCircle: return "\u{e119}"
                case .money: return "\u{0040}"
                case .moneyTransferIn: return "\u{e167}"
                case .moneyTransferOut: return "\u{e168}"
                case .moon: return "\u{e090}"
                case .musicalInstruments: return "\u{e086}"
                case .newWindow: return "\u{e05e}"
                case .noKiwicomGuarantee: return "\u{e208}"
                case .nonstop: return "\u{e120}"
                case .notification: return "\u{e018}"
                case .notificationAdd: return "\u{e195}"
                case .notificationOff: return "\u{e023}"
                case .notificationOn: return "\u{e025}"
                case .onlineCheckin: return "\u{e00f}"
                case .onlineCheckinOff: return "\u{e00e}"
                case .outlook: return "\u{e181}"
                case .paid: return "\u{e121}"
                case .parking: return "\u{e03e}"
                case .partners: return "\u{e164}"
                case .passenger: return "\u{0077}"
                case .passengerAdd: return "\u{0029}"
                case .passengerOutline: return "\u{e137}"
                case .passengerRemove: return "\u{e173}"
                case .passengers: return "\u{0028}"
                case .passport: return "\u{0051}"
                case .pet: return "\u{e043}"
                case .pharmacy: return "\u{e034}"
                case .phone: return "\u{e058}"
                case .playground: return "\u{e053}"
                case .plus: return "\u{e122}"
                case .plusCircle: return "\u{e027}"
                case .pool: return "\u{e123}"
                case .powerPlug: return "\u{e06f}"
                case .powerPlugOff: return "\u{0033}"
                case .priorityBoarding: return "\u{e08d}"
                case .profit: return "\u{e166}"
                case .promoCode: return "\u{e081}"
                case .qrCode: return "\u{e193}"
                case .questionCircle: return "\u{0046}"
                case .radar: return "\u{e198}"
                case .radiusSearch: return "\u{0064}"
                case .refund: return "\u{e165}"
                case .relax: return "\u{e046}"
                case .reload: return "\u{0032}"
                case .remove: return "\u{0057}"
                case .replace: return "\u{0049}"
                case .restaurant: return "\u{0031}"
                case .routeNoStops: return "\u{006f}"
                case .routeOneStop: return "\u{0071}"
                case .routeTwoStops: return "\u{0070}"
                case .search: return "\u{e07c}"
                case .seat: return "\u{e02a}"
                case .seatAisle: return "\u{e189}"
                case .seatExtraLegroom: return "\u{e190}"
                case .seatWindow: return "\u{e188}"
                case .security: return "\u{e146}"
                case .selfTransfer: return "\u{e020}"
                case .send: return "\u{004d}"
                case .settings: return "\u{0038}"
                case .share: return "\u{e016}"
                case .shareAndroid: return "\u{e068}"
                case .shareIos: return "\u{e163}"
                case .shopping: return "\u{e036}"
                case .showLess: return "\u{e124}"
                case .showMore: return "\u{e125}"
                case .sightseeing: return "\u{e015}"
                case .smoking: return "\u{e037}"
                case .smokingOff: return "\u{e126}"
                case .sort: return "\u{e171}"
                case .spa: return "\u{e04a}"
                case .sportEquipment: return "\u{e127}"
                case .sports: return "\u{e042}"
                case .starEmpty: return "\u{e08c}"
                case .starFull: return "\u{0023}"
                case .subway: return "\u{e06a}"
                case .suitcase: return "\u{e02d}"
                case .sun: return "\u{e096}"
                case .sunrise: return "\u{e08e}"
                case .taxi: return "\u{003b}"
                case .terminal: return "\u{e196}"
                case .termsAndConditions: return "\u{e0a4}"
                case .thumbDown: return "\u{e128}"
                case .thumbUp: return "\u{e01b}"
                case .ticket: return "\u{002e}"
                case .ticketOutline: return "\u{e138}"
                case .timelapse: return "\u{e000}"
                case .timer: return "\u{e177}"
                case .tips: return "\u{e047}"
                case .toilets: return "\u{e129}"
                case .train: return "\u{e028}"
                case .transmission: return "\u{e182}"
                case .trip: return "\u{e130}"
                case .twitter: return "\u{e131}"
                case .uber: return "\u{e162}"
                case .upload: return "\u{e172}"
                case .userGroup: return "\u{e192}"
                case .visa: return "\u{e132}"
                case .visibility: return "\u{e005}"
                case .visibilityOff: return "\u{e004}"
                case .walk: return "\u{e052}"
                case .wallet: return "\u{e133}"
                case .wheelchair: return "\u{e088}"
                case .wifi: return "\u{e062}"
                case .wifiOff: return "\u{005a}"
            }
        }
    }
}
