
// Generated by 'Automation/update_icons.py'
public extension Icon {

    enum Symbol: CaseIterable, Equatable, Sendable {
        /// Orbit `accommodation` icon symbol.
        case accommodation
        /// Orbit `accountCircle` icon symbol.
        case accountCircle
        /// Orbit `admin` icon symbol.
        case admin
        /// Orbit `ai` icon symbol.
        case ai
        /// Orbit `airConditioning` icon symbol.
        case airConditioning
        /// Orbit `airplane` icon symbol.
        case airplane
        /// Orbit `airplaneDown` icon symbol.
        case airplaneDown
        /// Orbit `airplaneLanding` icon symbol.
        case airplaneLanding
        /// Orbit `airplaneReturn` icon symbol.
        case airplaneReturn
        /// Orbit `airplaneTakeoff` icon symbol.
        case airplaneTakeoff
        /// Orbit `airplaneUp` icon symbol.
        case airplaneUp
        /// Orbit `airplaneUpOff` icon symbol.
        case airplaneUpOff
        /// Orbit `airportSecurity` icon symbol.
        case airportSecurity
        /// Orbit `alert` icon symbol.
        case alert
        /// Orbit `alertCircle` icon symbol.
        case alertCircle
        /// Orbit `alertOctagon` icon symbol.
        case alertOctagon
        /// Orbit `all` icon symbol.
        case all
        /// Orbit `ambulanceLight` icon symbol.
        case ambulanceLight
        /// Orbit `android` icon symbol.
        case android
        /// Orbit `anywhere` icon symbol.
        case anywhere
        /// Orbit `appNotification` icon symbol.
        case appNotification
        /// Orbit `apple` icon symbol.
        case apple
        /// Orbit `arrowBack` icon symbol.
        case arrowBack
        /// Orbit `arrowDown` icon symbol.
        case arrowDown
        /// Orbit `arrowUp` icon symbol.
        case arrowUp
        /// Orbit `atm` icon symbol.
        case atm
        /// Orbit `attachment` icon symbol.
        case attachment
        /// Orbit `baggageCabin` icon symbol.
        case baggageCabin
        /// Orbit `baggageCabinLight` icon symbol.
        case baggageCabinLight
        /// Orbit `baggageCabinNone` icon symbol.
        case baggageCabinNone
        /// Orbit `baggageCabinNoneLight` icon symbol.
        case baggageCabinNoneLight
        /// Orbit `baggageChecked10` icon symbol.
        case baggageChecked10
        /// Orbit `baggageChecked10Light` icon symbol.
        case baggageChecked10Light
        /// Orbit `baggageChecked10NoneLight` icon symbol.
        case baggageChecked10NoneLight
        /// Orbit `baggageChecked20` icon symbol.
        case baggageChecked20
        /// Orbit `baggageChecked20Light` icon symbol.
        case baggageChecked20Light
        /// Orbit `baggageChecked20NoneLight` icon symbol.
        case baggageChecked20NoneLight
        /// Orbit `baggageChecked30` icon symbol.
        case baggageChecked30
        /// Orbit `baggageChecked30Light` icon symbol.
        case baggageChecked30Light
        /// Orbit `baggageCheckedNone` icon symbol.
        case baggageCheckedNone
        /// Orbit `baggageCheckedNoneLight` icon symbol.
        case baggageCheckedNoneLight
        /// Orbit `baggagePersonal` icon symbol.
        case baggagePersonal
        /// Orbit `baggagePersonalLight` icon symbol.
        case baggagePersonalLight
        /// Orbit `baggagePersonalNone` icon symbol.
        case baggagePersonalNone
        /// Orbit `baggagePersonalNoneLight` icon symbol.
        case baggagePersonalNoneLight
        /// Orbit `baggageRecheck` icon symbol.
        case baggageRecheck
        /// Orbit `baggageSet` icon symbol.
        case baggageSet
        /// Orbit `baggageSetLight` icon symbol.
        case baggageSetLight
        /// Orbit `baggageStorage` icon symbol.
        case baggageStorage
        /// Orbit `bank` icon symbol.
        case bank
        /// Orbit `billingDetails` icon symbol.
        case billingDetails
        /// Orbit `boardingGate` icon symbol.
        case boardingGate
        /// Orbit `boat` icon symbol.
        case boat
        /// Orbit `bookmark` icon symbol.
        case bookmark
        /// Orbit `bug` icon symbol.
        case bug
        /// Orbit `bus` icon symbol.
        case bus
        /// Orbit `cake` icon symbol.
        case cake
        /// Orbit `calendar` icon symbol.
        case calendar
        /// Orbit `calendarAnytime` icon symbol.
        case calendarAnytime
        /// Orbit `calendarDuration` icon symbol.
        case calendarDuration
        /// Orbit `calendarRange` icon symbol.
        case calendarRange
        /// Orbit `calendarTripLength` icon symbol.
        case calendarTripLength
        /// Orbit `camera` icon symbol.
        case camera
        /// Orbit `car` icon symbol.
        case car
        /// Orbit `carDoor` icon symbol.
        case carDoor
        /// Orbit `carRental` icon symbol.
        case carRental
        /// Orbit `chart` icon symbol.
        case chart
        /// Orbit `chat` icon symbol.
        case chat
        /// Orbit `check` icon symbol.
        case check
        /// Orbit `checkCircle` icon symbol.
        case checkCircle
        /// Orbit `chevronBackward` icon symbol.
        case chevronBackward
        /// Orbit `chevronDoubleBackward` icon symbol.
        case chevronDoubleBackward
        /// Orbit `chevronDoubleForward` icon symbol.
        case chevronDoubleForward
        /// Orbit `chevronDown` icon symbol.
        case chevronDown
        /// Orbit `chevronForward` icon symbol.
        case chevronForward
        /// Orbit `chevronUp` icon symbol.
        case chevronUp
        /// Orbit `child` icon symbol.
        case child
        /// Orbit `childFriendly` icon symbol.
        case childFriendly
        /// Orbit `circle` icon symbol.
        case circle
        /// Orbit `circleEmpty` icon symbol.
        case circleEmpty
        /// Orbit `circleFilled` icon symbol.
        case circleFilled
        /// Orbit `circleSmall` icon symbol.
        case circleSmall
        /// Orbit `circleSmallEmpty` icon symbol.
        case circleSmallEmpty
        /// Orbit `city` icon symbol.
        case city
        /// Orbit `clock` icon symbol.
        case clock
        /// Orbit `close` icon symbol.
        case close
        /// Orbit `closeCircle` icon symbol.
        case closeCircle
        /// Orbit `cocktail` icon symbol.
        case cocktail
        /// Orbit `code` icon symbol.
        case code
        /// Orbit `code.kiwi` icon symbol.
        case codeKiwi
        /// Orbit `coffee` icon symbol.
        case coffee
        /// Orbit `colorPicker` icon symbol.
        case colorPicker
        /// Orbit `coloredFacebook` icon symbol.
        case coloredFacebook
        /// Orbit `coloredImessage` icon symbol.
        case coloredImessage
        /// Orbit `coloredMessenger` icon symbol.
        case coloredMessenger
        /// Orbit `coloredSignal` icon symbol.
        case coloredSignal
        /// Orbit `coloredTelegram` icon symbol.
        case coloredTelegram
        /// Orbit `coloredViber` icon symbol.
        case coloredViber
        /// Orbit `coloredWhatsapp` icon symbol.
        case coloredWhatsapp
        /// Orbit `compare` icon symbol.
        case compare
        /// Orbit `compass` icon symbol.
        case compass
        /// Orbit `contactEmail` icon symbol.
        case contactEmail
        /// Orbit `copy` icon symbol.
        case copy
        /// Orbit `creditCard` icon symbol.
        case creditCard
        /// Orbit `customerSupport` icon symbol.
        case customerSupport
        /// Orbit `dashboard` icon symbol.
        case dashboard
        /// Orbit `deals` icon symbol.
        case deals
        /// Orbit `dealsV2` icon symbol.
        case dealsV2
        /// Orbit `deviceDesktop` icon symbol.
        case deviceDesktop
        /// Orbit `deviceMobile` icon symbol.
        case deviceMobile
        /// Orbit `diamond` icon symbol.
        case diamond
        /// Orbit `document` icon symbol.
        case document
        /// Orbit `download` icon symbol.
        case download
        /// Orbit `duplicate` icon symbol.
        case duplicate
        /// Orbit `edit` icon symbol.
        case edit
        /// Orbit `editOff` icon symbol.
        case editOff
        /// Orbit `email` icon symbol.
        case email
        /// Orbit `entertainment` icon symbol.
        case entertainment
        /// Orbit `exchange` icon symbol.
        case exchange
        /// Orbit `facebook` icon symbol.
        case facebook
        /// Orbit `familyAll` icon symbol.
        case familyAll
        /// Orbit `familyHalf` icon symbol.
        case familyHalf
        /// Orbit `feedback` icon symbol.
        case feedback
        /// Orbit `filters` icon symbol.
        case filters
        /// Orbit `flash` icon symbol.
        case flash
        /// Orbit `flightDirect` icon symbol.
        case flightDirect
        /// Orbit `flightMulticity` icon symbol.
        case flightMulticity
        /// Orbit `flightNomad` icon symbol.
        case flightNomad
        /// Orbit `flightReturn` icon symbol.
        case flightReturn
        /// Orbit `flightServices` icon symbol.
        case flightServices
        /// Orbit `fuel` icon symbol.
        case fuel
        /// Orbit `fullScreen` icon symbol.
        case fullScreen
        /// Orbit `fullScreenOff` icon symbol.
        case fullScreenOff
        /// Orbit `gallery` icon symbol.
        case gallery
        /// Orbit `genderMan` icon symbol.
        case genderMan
        /// Orbit `genderWoman` icon symbol.
        case genderWoman
        /// Orbit `github` icon symbol.
        case github
        /// Orbit `google` icon symbol.
        case google
        /// Orbit `googlePlay` icon symbol.
        case googlePlay
        /// Orbit `gpsFixed` icon symbol.
        case gpsFixed
        /// Orbit `gpsIos` icon symbol.
        case gpsIos
        /// Orbit `gpsNotFixed` icon symbol.
        case gpsNotFixed
        /// Orbit `gpsOff` icon symbol.
        case gpsOff
        /// Orbit `grid` icon symbol.
        case grid
        /// Orbit `gym` icon symbol.
        case gym
        /// Orbit `heart` icon symbol.
        case heart
        /// Orbit `heartOutline` icon symbol.
        case heartOutline
        /// Orbit `history` icon symbol.
        case history
        /// Orbit `hospitalSignLight` icon symbol.
        case hospitalSignLight
        /// Orbit `inbox` icon symbol.
        case inbox
        /// Orbit `infant` icon symbol.
        case infant
        /// Orbit `informationCircle` icon symbol.
        case informationCircle
        /// Orbit `informationCircleLight` icon symbol.
        case informationCircleLight
        /// Orbit `instagram` icon symbol.
        case instagram
        /// Orbit `insurance` icon symbol.
        case insurance
        /// Orbit `insuranceConfirmed` icon symbol.
        case insuranceConfirmed
        /// Orbit `insuranceOff` icon symbol.
        case insuranceOff
        /// Orbit `invoice` icon symbol.
        case invoice
        /// Orbit `itemCompleted` icon symbol.
        case itemCompleted
        /// Orbit `kiwicom` icon symbol.
        case kiwicom
        /// Orbit `kiwicomCare` icon symbol.
        case kiwicomCare
        /// Orbit `kiwicomGuarantee` icon symbol.
        case kiwicomGuarantee
        /// Orbit `kiwicomNoGuarantee` icon symbol.
        case kiwicomNoGuarantee
        /// Orbit `legalExpertsLight` icon symbol.
        case legalExpertsLight
        /// Orbit `leisure` icon symbol.
        case leisure
        /// Orbit `link` icon symbol.
        case link
        /// Orbit `linkedin` icon symbol.
        case linkedin
        /// Orbit `list` icon symbol.
        case list
        /// Orbit `location` icon symbol.
        case location
        /// Orbit `locationA` icon symbol.
        case locationA
        /// Orbit `locationAdd` icon symbol.
        case locationAdd
        /// Orbit `locationB` icon symbol.
        case locationB
        /// Orbit `locationC` icon symbol.
        case locationC
        /// Orbit `locationD` icon symbol.
        case locationD
        /// Orbit `locationE` icon symbol.
        case locationE
        /// Orbit `locationF` icon symbol.
        case locationF
        /// Orbit `locationG` icon symbol.
        case locationG
        /// Orbit `locationH` icon symbol.
        case locationH
        /// Orbit `locationI` icon symbol.
        case locationI
        /// Orbit `locationJ` icon symbol.
        case locationJ
        /// Orbit `lock` icon symbol.
        case lock
        /// Orbit `lockOpen` icon symbol.
        case lockOpen
        /// Orbit `logout` icon symbol.
        case logout
        /// Orbit `lounge` icon symbol.
        case lounge
        /// Orbit `map` icon symbol.
        case map
        /// Orbit `markdown` icon symbol.
        case markdown
        /// Orbit `meal` icon symbol.
        case meal
        /// Orbit `mealLight` icon symbol.
        case mealLight
        /// Orbit `medicalInsuranceLight` icon symbol.
        case medicalInsuranceLight
        /// Orbit `medicalProtectionLight` icon symbol.
        case medicalProtectionLight
        /// Orbit `menuCircle` icon symbol.
        case menuCircle
        /// Orbit `menuHamburger` icon symbol.
        case menuHamburger
        /// Orbit `menuKebab` icon symbol.
        case menuKebab
        /// Orbit `menuMeatballs` icon symbol.
        case menuMeatballs
        /// Orbit `messages` icon symbol.
        case messages
        /// Orbit `messagesOutline` icon symbol.
        case messagesOutline
        /// Orbit `minus` icon symbol.
        case minus
        /// Orbit `minusCircle` icon symbol.
        case minusCircle
        /// Orbit `money` icon symbol.
        case money
        /// Orbit `moneyTransferIn` icon symbol.
        case moneyTransferIn
        /// Orbit `moneyTransferOut` icon symbol.
        case moneyTransferOut
        /// Orbit `moon` icon symbol.
        case moon
        /// Orbit `musicalInstruments` icon symbol.
        case musicalInstruments
        /// Orbit `newWindow` icon symbol.
        case newWindow
        /// Orbit `noFlash` icon symbol.
        case noFlash
        /// Orbit `noRefund` icon symbol.
        case noRefund
        /// Orbit `noRescheduling` icon symbol.
        case noRescheduling
        /// Orbit `noWifiLight` icon symbol.
        case noWifiLight
        /// Orbit `nonstop` icon symbol.
        case nonstop
        /// Orbit `notification` icon symbol.
        case notification
        /// Orbit `notificationAdd` icon symbol.
        case notificationAdd
        /// Orbit `notificationOff` icon symbol.
        case notificationOff
        /// Orbit `notificationOn` icon symbol.
        case notificationOn
        /// Orbit `onlineCheckin` icon symbol.
        case onlineCheckin
        /// Orbit `onlineCheckinOff` icon symbol.
        case onlineCheckinOff
        /// Orbit `outlook` icon symbol.
        case outlook
        /// Orbit `paid` icon symbol.
        case paid
        /// Orbit `parking` icon symbol.
        case parking
        /// Orbit `partners` icon symbol.
        case partners
        /// Orbit `passenger` icon symbol.
        case passenger
        /// Orbit `passengerAdd` icon symbol.
        case passengerAdd
        /// Orbit `passengerOutline` icon symbol.
        case passengerOutline
        /// Orbit `passengerRemove` icon symbol.
        case passengerRemove
        /// Orbit `passengers` icon symbol.
        case passengers
        /// Orbit `passport` icon symbol.
        case passport
        /// Orbit `pet` icon symbol.
        case pet
        /// Orbit `pharmacy` icon symbol.
        case pharmacy
        /// Orbit `phone` icon symbol.
        case phone
        /// Orbit `phoneUpdatesLight` icon symbol.
        case phoneUpdatesLight
        /// Orbit `pin` icon symbol.
        case pin
        /// Orbit `pinOutline` icon symbol.
        case pinOutline
        /// Orbit `placeholder` icon symbol.
        case placeholder
        /// Orbit `play` icon symbol.
        case play
        /// Orbit `playground` icon symbol.
        case playground
        /// Orbit `plus` icon symbol.
        case plus
        /// Orbit `plusCircle` icon symbol.
        case plusCircle
        /// Orbit `plusMinus` icon symbol.
        case plusMinus
        /// Orbit `pool` icon symbol.
        case pool
        /// Orbit `powerPlug` icon symbol.
        case powerPlug
        /// Orbit `powerPlugOff` icon symbol.
        case powerPlugOff
        /// Orbit `priceChange` icon symbol.
        case priceChange
        /// Orbit `priorityBoarding` icon symbol.
        case priorityBoarding
        /// Orbit `priorityBoardingLight` icon symbol.
        case priorityBoardingLight
        /// Orbit `profit` icon symbol.
        case profit
        /// Orbit `promoCode` icon symbol.
        case promoCode
        /// Orbit `qrCode` icon symbol.
        case qrCode
        /// Orbit `questionCircle` icon symbol.
        case questionCircle
        /// Orbit `radar` icon symbol.
        case radar
        /// Orbit `radiusSearch` icon symbol.
        case radiusSearch
        /// Orbit `rebookingLight` icon symbol.
        case rebookingLight
        /// Orbit `rebookingNoneLight` icon symbol.
        case rebookingNoneLight
        /// Orbit `refund` icon symbol.
        case refund
        /// Orbit `refundLight` icon symbol.
        case refundLight
        /// Orbit `refundNoneLight` icon symbol.
        case refundNoneLight
        /// Orbit `relax` icon symbol.
        case relax
        /// Orbit `reload` icon symbol.
        case reload
        /// Orbit `remove` icon symbol.
        case remove
        /// Orbit `replace` icon symbol.
        case replace
        /// Orbit `restaurant` icon symbol.
        case restaurant
        /// Orbit `routeNoStops` icon symbol.
        case routeNoStops
        /// Orbit `routeOneStop` icon symbol.
        case routeOneStop
        /// Orbit `routeTwoStops` icon symbol.
        case routeTwoStops
        /// Orbit `search` icon symbol.
        case search
        /// Orbit `seat` icon symbol.
        case seat
        /// Orbit `seatAisle` icon symbol.
        case seatAisle
        /// Orbit `seatAisleLight` icon symbol.
        case seatAisleLight
        /// Orbit `seatDefaultLight` icon symbol.
        case seatDefaultLight
        /// Orbit `seatExtraLegroom` icon symbol.
        case seatExtraLegroom
        /// Orbit `seatLight` icon symbol.
        case seatLight
        /// Orbit `seatWindow` icon symbol.
        case seatWindow
        /// Orbit `seatWindowLight` icon symbol.
        case seatWindowLight
        /// Orbit `security` icon symbol.
        case security
        /// Orbit `selfTransfer` icon symbol.
        case selfTransfer
        /// Orbit `send` icon symbol.
        case send
        /// Orbit `settings` icon symbol.
        case settings
        /// Orbit `share` icon symbol.
        case share
        /// Orbit `shareAndroid` icon symbol.
        case shareAndroid
        /// Orbit `shareAndroidOutline` icon symbol.
        case shareAndroidOutline
        /// Orbit `shareIos` icon symbol.
        case shareIos
        /// Orbit `shopping` icon symbol.
        case shopping
        /// Orbit `showLess` icon symbol.
        case showLess
        /// Orbit `showMore` icon symbol.
        case showMore
        /// Orbit `sightseeing` icon symbol.
        case sightseeing
        /// Orbit `sign` icon symbol.
        case sign
        /// Orbit `smoking` icon symbol.
        case smoking
        /// Orbit `smokingOff` icon symbol.
        case smokingOff
        /// Orbit `sms` icon symbol.
        case sms
        /// Orbit `sort` icon symbol.
        case sort
        /// Orbit `spa` icon symbol.
        case spa
        /// Orbit `sportEquipment` icon symbol.
        case sportEquipment
        /// Orbit `sports` icon symbol.
        case sports
        /// Orbit `stackoverflow` icon symbol.
        case stackoverflow
        /// Orbit `starEmpty` icon symbol.
        case starEmpty
        /// Orbit `starFull` icon symbol.
        case starFull
        /// Orbit `subway` icon symbol.
        case subway
        /// Orbit `suitcase` icon symbol.
        case suitcase
        /// Orbit `sun` icon symbol.
        case sun
        /// Orbit `sunrise` icon symbol.
        case sunrise
        /// Orbit `taxi` icon symbol.
        case taxi
        /// Orbit `terminal` icon symbol.
        case terminal
        /// Orbit `termsAndConditions` icon symbol.
        case termsAndConditions
        /// Orbit `thumbDown` icon symbol.
        case thumbDown
        /// Orbit `thumbUp` icon symbol.
        case thumbUp
        /// Orbit `ticket` icon symbol.
        case ticket
        /// Orbit `ticketOutline` icon symbol.
        case ticketOutline
        /// Orbit `tiktok` icon symbol.
        case tiktok
        /// Orbit `timelapse` icon symbol.
        case timelapse
        /// Orbit `timer` icon symbol.
        case timer
        /// Orbit `tips` icon symbol.
        case tips
        /// Orbit `toilets` icon symbol.
        case toilets
        /// Orbit `train` icon symbol.
        case train
        /// Orbit `transmission` icon symbol.
        case transmission
        /// Orbit `trip` icon symbol.
        case trip
        /// Orbit `tripUpdatesLight` icon symbol.
        case tripUpdatesLight
        /// Orbit `uber` icon symbol.
        case uber
        /// Orbit `upload` icon symbol.
        case upload
        /// Orbit `userGroup` icon symbol.
        case userGroup
        /// Orbit `userSingle` icon symbol.
        case userSingle
        /// Orbit `visa` icon symbol.
        case visa
        /// Orbit `visibility` icon symbol.
        case visibility
        /// Orbit `visibilityOff` icon symbol.
        case visibilityOff
        /// Orbit `walk` icon symbol.
        case walk
        /// Orbit `wallet` icon symbol.
        case wallet
        /// Orbit `wheelchair` icon symbol.
        case wheelchair
        /// Orbit `wifi` icon symbol.
        case wifi
        /// Orbit `wifiLight` icon symbol.
        case wifiLight
        /// Orbit `wifiOff` icon symbol.
        case wifiOff
        /// Orbit `x` icon symbol.
        case x
        /// Orbit `youtube` icon symbol.
        case youtube

        public var value: String {
            switch self {
                case .accommodation: "\u{2698}"
                case .accountCircle: "\u{2008}"
                case .admin: "\u{2679}"
                case .ai: "\u{9860}"
                case .airConditioning: "\u{2858}"
                case .airplane: "\u{4947}"
                case .airplaneDown: "\u{2681}"
                case .airplaneLanding: "\u{2720}"
                case .airplaneReturn: "\u{5982}"
                case .airplaneTakeoff: "\u{2864}"
                case .airplaneUp: "\u{9442}"
                case .airplaneUpOff: "\u{9310}"
                case .airportSecurity: "\u{5410}"
                case .alert: "\u{2690}"
                case .alertCircle: "\u{2685}"
                case .alertOctagon: "\u{2724}"
                case .all: "\u{3671}"
                case .ambulanceLight: "\u{0596}"
                case .android: "\u{2402}"
                case .anywhere: "\u{3751}"
                case .appNotification: "\u{5083}"
                case .apple: "\u{1211}"
                case .arrowBack: "\u{0200}"
                case .arrowDown: "\u{9572}"
                case .arrowUp: "\u{2781}"
                case .atm: "\u{2728}"
                case .attachment: "\u{4440}"
                case .baggageCabin: "\u{2799}"
                case .baggageCabinLight: "\u{2521}"
                case .baggageCabinNone: "\u{2826}"
                case .baggageCabinNoneLight: "\u{3427}"
                case .baggageChecked10: "\u{9038}"
                case .baggageChecked10Light: "\u{9187}"
                case .baggageChecked10NoneLight: "\u{0226}"
                case .baggageChecked20: "\u{2806}"
                case .baggageChecked20Light: "\u{1706}"
                case .baggageChecked20NoneLight: "\u{0245}"
                case .baggageChecked30: "\u{2813}"
                case .baggageChecked30Light: "\u{4855}"
                case .baggageCheckedNone: "\u{2836}"
                case .baggageCheckedNoneLight: "\u{2193}"
                case .baggagePersonal: "\u{2909}"
                case .baggagePersonalLight: "\u{2461}"
                case .baggagePersonalNone: "\u{2660}"
                case .baggagePersonalNoneLight: "\u{1701}"
                case .baggageRecheck: "\u{7766}"
                case .baggageSet: "\u{8851}"
                case .baggageSetLight: "\u{3296}"
                case .baggageStorage: "\u{2845}"
                case .bank: "\u{6692}"
                case .billingDetails: "\u{2707}"
                case .boardingGate: "\u{9372}"
                case .boat: "\u{2788}"
                case .bookmark: "\u{9344}"
                case .bug: "\u{2726}"
                case .bus: "\u{2808}"
                case .cake: "\u{4460}"
                case .calendar: "\u{2661}"
                case .calendarAnytime: "\u{4527}"
                case .calendarDuration: "\u{4904}"
                case .calendarRange: "\u{5952}"
                case .calendarTripLength: "\u{3556}"
                case .camera: "\u{2768}"
                case .car: "\u{2664}"
                case .carDoor: "\u{2665}"
                case .carRental: "\u{2862}"
                case .chart: "\u{6925}"
                case .chat: "\u{8647}"
                case .check: "\u{2903}"
                case .checkCircle: "\u{2740}"
                case .chevronBackward: "\u{2822}"
                case .chevronDoubleBackward: "\u{2264}"
                case .chevronDoubleForward: "\u{7058}"
                case .chevronDown: "\u{2667}"
                case .chevronForward: "\u{2668}"
                case .chevronUp: "\u{2669}"
                case .child: "\u{2670}"
                case .childFriendly: "\u{2671}"
                case .circle: "\u{2672}"
                case .circleEmpty: "\u{5486}"
                case .circleFilled: "\u{2674}"
                case .circleSmall: "\u{8053}"
                case .circleSmallEmpty: "\u{9571}"
                case .city: "\u{2914}"
                case .clock: "\u{8108}"
                case .close: "\u{2889}"
                case .closeCircle: "\u{2853}"
                case .cocktail: "\u{2927}"
                case .code: "\u{5056}"
                case .codeKiwi: "\u{5988}"
                case .coffee: "\u{2713}"
                case .colorPicker: "\u{8770}"
                case .coloredFacebook: "\u{2129}"
                case .coloredImessage: "\u{9052}"
                case .coloredMessenger: "\u{4407}"
                case .coloredSignal: "\u{4623}"
                case .coloredTelegram: "\u{5916}"
                case .coloredViber: "\u{6059}"
                case .coloredWhatsapp: "\u{3046}"
                case .compare: "\u{2680}"
                case .compass: "\u{4816}"
                case .contactEmail: "\u{2684}"
                case .copy: "\u{7844}"
                case .creditCard: "\u{2686}"
                case .customerSupport: "\u{2688}"
                case .dashboard: "\u{1469}"
                case .deals: "\u{2691}"
                case .dealsV2: "\u{6728}"
                case .deviceDesktop: "\u{1774}"
                case .deviceMobile: "\u{3069}"
                case .diamond: "\u{8630}"
                case .document: "\u{2696}"
                case .download: "\u{2697}"
                case .duplicate: "\u{9494}"
                case .edit: "\u{6036}"
                case .editOff: "\u{3372}"
                case .email: "\u{3953}"
                case .entertainment: "\u{2709}"
                case .exchange: "\u{1707}"
                case .facebook: "\u{4121}"
                case .familyAll: "\u{2745}"
                case .familyHalf: "\u{2714}"
                case .feedback: "\u{2751}"
                case .filters: "\u{2715}"
                case .flash: "\u{9010}"
                case .flightDirect: "\u{7084}"
                case .flightMulticity: "\u{7878}"
                case .flightNomad: "\u{2723}"
                case .flightReturn: "\u{8043}"
                case .flightServices: "\u{8447}"
                case .fuel: "\u{9902}"
                case .fullScreen: "\u{2730}"
                case .fullScreenOff: "\u{6821}"
                case .gallery: "\u{2731}"
                case .genderMan: "\u{7062}"
                case .genderWoman: "\u{2734}"
                case .github: "\u{8955}"
                case .google: "\u{5959}"
                case .googlePlay: "\u{1038}"
                case .gpsFixed: "\u{6683}"
                case .gpsIos: "\u{8993}"
                case .gpsNotFixed: "\u{1504}"
                case .gpsOff: "\u{2737}"
                case .grid: "\u{5681}"
                case .gym: "\u{7005}"
                case .heart: "\u{1009}"
                case .heartOutline: "\u{1019}"
                case .history: "\u{2803}"
                case .hospitalSignLight: "\u{0581}"
                case .inbox: "\u{6431}"
                case .infant: "\u{9347}"
                case .informationCircle: "\u{2814}"
                case .informationCircleLight: "\u{0257}"
                case .instagram: "\u{7300}"
                case .insurance: "\u{2805}"
                case .insuranceConfirmed: "\u{2786}"
                case .insuranceOff: "\u{4031}"
                case .invoice: "\u{2702}"
                case .itemCompleted: "\u{5244}"
                case .kiwicom: "\u{2844}"
                case .kiwicomCare: "\u{9753}"
                case .kiwicomGuarantee: "\u{2319}"
                case .kiwicomNoGuarantee: "\u{2775}"
                case .legalExpertsLight: "\u{0935}"
                case .leisure: "\u{8309}"
                case .link: "\u{9259}"
                case .linkedin: "\u{9652}"
                case .list: "\u{7893}"
                case .location: "\u{9892}"
                case .locationA: "\u{9233}"
                case .locationAdd: "\u{6403}"
                case .locationB: "\u{2850}"
                case .locationC: "\u{2875}"
                case .locationD: "\u{2710}"
                case .locationE: "\u{1680}"
                case .locationF: "\u{2869}"
                case .locationG: "\u{2750}"
                case .locationH: "\u{3445}"
                case .locationI: "\u{1974}"
                case .locationJ: "\u{2924}"
                case .lock: "\u{2753}"
                case .lockOpen: "\u{2755}"
                case .logout: "\u{3794}"
                case .lounge: "\u{2880}"
                case .map: "\u{2758}"
                case .markdown: "\u{8187}"
                case .meal: "\u{2760}"
                case .mealLight: "\u{0262}"
                case .medicalInsuranceLight: "\u{0586}"
                case .medicalProtectionLight: "\u{0578}"
                case .menuCircle: "\u{0114}"
                case .menuHamburger: "\u{2761}"
                case .menuKebab: "\u{6385}"
                case .menuMeatballs: "\u{7789}"
                case .messages: "\u{2764}"
                case .messagesOutline: "\u{9970}"
                case .minus: "\u{2766}"
                case .minusCircle: "\u{4552}"
                case .money: "\u{8910}"
                case .moneyTransferIn: "\u{9169}"
                case .moneyTransferOut: "\u{2770}"
                case .moon: "\u{2771}"
                case .musicalInstruments: "\u{2802}"
                case .newWindow: "\u{2101}"
                case .noFlash: "\u{6933}"
                case .noRefund: "\u{2776}"
                case .noRescheduling: "\u{2777}"
                case .noWifiLight: "\u{0566}"
                case .nonstop: "\u{2778}"
                case .notification: "\u{2779}"
                case .notificationAdd: "\u{9535}"
                case .notificationOff: "\u{7252}"
                case .notificationOn: "\u{9742}"
                case .onlineCheckin: "\u{8410}"
                case .onlineCheckinOff: "\u{8777}"
                case .outlook: "\u{5080}"
                case .paid: "\u{2886}"
                case .parking: "\u{2865}"
                case .partners: "\u{2883}"
                case .passenger: "\u{2832}"
                case .passengerAdd: "\u{4935}"
                case .passengerOutline: "\u{6092}"
                case .passengerRemove: "\u{2867}"
                case .passengers: "\u{2111}"
                case .passport: "\u{5491}"
                case .pet: "\u{2893}"
                case .pharmacy: "\u{2925}"
                case .phone: "\u{2783}"
                case .phoneUpdatesLight: "\u{0562}"
                case .pin: "\u{3914}"
                case .pinOutline: "\u{1081}"
                case .placeholder: "\u{1255}"
                case .play: "\u{6189}"
                case .playground: "\u{6111}"
                case .plus: "\u{3586}"
                case .plusCircle: "\u{2789}"
                case .plusMinus: "\u{4217}"
                case .pool: "\u{9337}"
                case .powerPlug: "\u{2827}"
                case .powerPlugOff: "\u{8785}"
                case .priceChange: "\u{3027}"
                case .priorityBoarding: "\u{2874}"
                case .priorityBoardingLight: "\u{0218}"
                case .profit: "\u{7636}"
                case .promoCode: "\u{2795}"
                case .qrCode: "\u{2801}"
                case .questionCircle: "\u{2915}"
                case .radar: "\u{2797}"
                case .radiusSearch: "\u{2785}"
                case .rebookingLight: "\u{7002}"
                case .rebookingNoneLight: "\u{8997}"
                case .refund: "\u{2754}"
                case .refundLight: "\u{9565}"
                case .refundNoneLight: "\u{7572}"
                case .relax: "\u{9709}"
                case .reload: "\u{2752}"
                case .remove: "\u{2807}"
                case .replace: "\u{9641}"
                case .restaurant: "\u{8995}"
                case .routeNoStops: "\u{1734}"
                case .routeOneStop: "\u{5253}"
                case .routeTwoStops: "\u{8469}"
                case .search: "\u{2887}"
                case .seat: "\u{2833}"
                case .seatAisle: "\u{2999}"
                case .seatAisleLight: "\u{0541}"
                case .seatDefaultLight: "\u{0539}"
                case .seatExtraLegroom: "\u{2817}"
                case .seatLight: "\u{4998}"
                case .seatWindow: "\u{9964}"
                case .seatWindowLight: "\u{0540}"
                case .security: "\u{8185}"
                case .selfTransfer: "\u{2787}"
                case .send: "\u{2821}"
                case .settings: "\u{2825}"
                case .share: "\u{9200}"
                case .shareAndroid: "\u{2835}"
                case .shareAndroidOutline: "\u{9305}"
                case .shareIos: "\u{6041}"
                case .shopping: "\u{2896}"
                case .showLess: "\u{2884}"
                case .showMore: "\u{5137}"
                case .sightseeing: "\u{3309}"
                case .sign: "\u{2841}"
                case .smoking: "\u{7198}"
                case .smokingOff: "\u{4702}"
                case .sms: "\u{7270}"
                case .sort: "\u{1188}"
                case .spa: "\u{2870}"
                case .sportEquipment: "\u{2855}"
                case .sports: "\u{2916}"
                case .stackoverflow: "\u{3239}"
                case .starEmpty: "\u{2866}"
                case .starFull: "\u{2876}"
                case .subway: "\u{7603}"
                case .suitcase: "\u{2908}"
                case .sun: "\u{2712}"
                case .sunrise: "\u{2881}"
                case .taxi: "\u{1833}"
                case .terminal: "\u{2165}"
                case .termsAndConditions: "\u{2843}"
                case .thumbDown: "\u{4945}"
                case .thumbUp: "\u{9504}"
                case .ticket: "\u{2888}"
                case .ticketOutline: "\u{2476}"
                case .tiktok: "\u{2167}"
                case .timelapse: "\u{2894}"
                case .timer: "\u{2231}"
                case .tips: "\u{4114}"
                case .toilets: "\u{7816}"
                case .train: "\u{1576}"
                case .transmission: "\u{8486}"
                case .trip: "\u{2911}"
                case .tripUpdatesLight: "\u{0564}"
                case .uber: "\u{7053}"
                case .upload: "\u{2746}"
                case .userGroup: "\u{2757}"
                case .userSingle: "\u{0224}"
                case .visa: "\u{3991}"
                case .visibility: "\u{7489}"
                case .visibilityOff: "\u{4122}"
                case .walk: "\u{8879}"
                case .wallet: "\u{3772}"
                case .wheelchair: "\u{2919}"
                case .wifi: "\u{4322}"
                case .wifiLight: "\u{0565}"
                case .wifiOff: "\u{1140}"
                case .x: "\u{1007}"
                case .youtube: "\u{7992}"
            }
        }
    }
}
