
// Generated by 'Automation/update_icons.py'
public extension Icon.Content {

    /// Absence of Orbit icon.
    static let none: Self = .symbol(.none)
    /// Orbit `accommodation` icon symbol with unspecified color.
    static let accommodation: Self = .symbol(.accommodation)
    /// Orbit `accountCircle` icon symbol with unspecified color.
    static let accountCircle: Self = .symbol(.accountCircle)
    /// Orbit `admin` icon symbol with unspecified color.
    static let admin: Self = .symbol(.admin)
    /// Orbit `ai` icon symbol with unspecified color.
    static let ai: Self = .symbol(.ai)
    /// Orbit `airConditioning` icon symbol with unspecified color.
    static let airConditioning: Self = .symbol(.airConditioning)
    /// Orbit `airplane` icon symbol with unspecified color.
    static let airplane: Self = .symbol(.airplane)
    /// Orbit `airplaneDown` icon symbol with unspecified color.
    static let airplaneDown: Self = .symbol(.airplaneDown)
    /// Orbit `airplaneLanding` icon symbol with unspecified color.
    static let airplaneLanding: Self = .symbol(.airplaneLanding)
    /// Orbit `airplaneReturn` icon symbol with unspecified color.
    static let airplaneReturn: Self = .symbol(.airplaneReturn)
    /// Orbit `airplaneTakeoff` icon symbol with unspecified color.
    static let airplaneTakeoff: Self = .symbol(.airplaneTakeoff)
    /// Orbit `airplaneUp` icon symbol with unspecified color.
    static let airplaneUp: Self = .symbol(.airplaneUp)
    /// Orbit `airplaneUpOff` icon symbol with unspecified color.
    static let airplaneUpOff: Self = .symbol(.airplaneUpOff)
    /// Orbit `airportSecurity` icon symbol with unspecified color.
    static let airportSecurity: Self = .symbol(.airportSecurity)
    /// Orbit `alert` icon symbol with unspecified color.
    static let alert: Self = .symbol(.alert)
    /// Orbit `alertCircle` icon symbol with unspecified color.
    static let alertCircle: Self = .symbol(.alertCircle)
    /// Orbit `alertOctagon` icon symbol with unspecified color.
    static let alertOctagon: Self = .symbol(.alertOctagon)
    /// Orbit `all` icon symbol with unspecified color.
    static let all: Self = .symbol(.all)
    /// Orbit `android` icon symbol with unspecified color.
    static let android: Self = .symbol(.android)
    /// Orbit `anywhere` icon symbol with unspecified color.
    static let anywhere: Self = .symbol(.anywhere)
    /// Orbit `appNotification` icon symbol with unspecified color.
    static let appNotification: Self = .symbol(.appNotification)
    /// Orbit `apple` icon symbol with unspecified color.
    static let apple: Self = .symbol(.apple)
    /// Orbit `arrowDown` icon symbol with unspecified color.
    static let arrowDown: Self = .symbol(.arrowDown)
    /// Orbit `arrowUp` icon symbol with unspecified color.
    static let arrowUp: Self = .symbol(.arrowUp)
    /// Orbit `atm` icon symbol with unspecified color.
    static let atm: Self = .symbol(.atm)
    /// Orbit `attachment` icon symbol with unspecified color.
    static let attachment: Self = .symbol(.attachment)
    /// Orbit `baggageCabin` icon symbol with unspecified color.
    static let baggageCabin: Self = .symbol(.baggageCabin)
    /// Orbit `baggageCabinNone` icon symbol with unspecified color.
    static let baggageCabinNone: Self = .symbol(.baggageCabinNone)
    /// Orbit `baggageChecked10` icon symbol with unspecified color.
    static let baggageChecked10: Self = .symbol(.baggageChecked10)
    /// Orbit `baggageChecked20` icon symbol with unspecified color.
    static let baggageChecked20: Self = .symbol(.baggageChecked20)
    /// Orbit `baggageChecked30` icon symbol with unspecified color.
    static let baggageChecked30: Self = .symbol(.baggageChecked30)
    /// Orbit `baggageCheckedNone` icon symbol with unspecified color.
    static let baggageCheckedNone: Self = .symbol(.baggageCheckedNone)
    /// Orbit `baggagePersonal` icon symbol with unspecified color.
    static let baggagePersonal: Self = .symbol(.baggagePersonal)
    /// Orbit `baggagePersonalNone` icon symbol with unspecified color.
    static let baggagePersonalNone: Self = .symbol(.baggagePersonalNone)
    /// Orbit `baggageRecheck` icon symbol with unspecified color.
    static let baggageRecheck: Self = .symbol(.baggageRecheck)
    /// Orbit `baggageSet` icon symbol with unspecified color.
    static let baggageSet: Self = .symbol(.baggageSet)
    /// Orbit `baggageStorage` icon symbol with unspecified color.
    static let baggageStorage: Self = .symbol(.baggageStorage)
    /// Orbit `billingDetails` icon symbol with unspecified color.
    static let billingDetails: Self = .symbol(.billingDetails)
    /// Orbit `boardingGate` icon symbol with unspecified color.
    static let boardingGate: Self = .symbol(.boardingGate)
    /// Orbit `boat` icon symbol with unspecified color.
    static let boat: Self = .symbol(.boat)
    /// Orbit `bookmark` icon symbol with unspecified color.
    static let bookmark: Self = .symbol(.bookmark)
    /// Orbit `bug` icon symbol with unspecified color.
    static let bug: Self = .symbol(.bug)
    /// Orbit `bus` icon symbol with unspecified color.
    static let bus: Self = .symbol(.bus)
    /// Orbit `cake` icon symbol with unspecified color.
    static let cake: Self = .symbol(.cake)
    /// Orbit `calendar` icon symbol with unspecified color.
    static let calendar: Self = .symbol(.calendar)
    /// Orbit `calendarAnytime` icon symbol with unspecified color.
    static let calendarAnytime: Self = .symbol(.calendarAnytime)
    /// Orbit `calendarRange` icon symbol with unspecified color.
    static let calendarRange: Self = .symbol(.calendarRange)
    /// Orbit `calendarTripLength` icon symbol with unspecified color.
    static let calendarTripLength: Self = .symbol(.calendarTripLength)
    /// Orbit `camera` icon symbol with unspecified color.
    static let camera: Self = .symbol(.camera)
    /// Orbit `car` icon symbol with unspecified color.
    static let car: Self = .symbol(.car)
    /// Orbit `carDoor` icon symbol with unspecified color.
    static let carDoor: Self = .symbol(.carDoor)
    /// Orbit `carRental` icon symbol with unspecified color.
    static let carRental: Self = .symbol(.carRental)
    /// Orbit `chart` icon symbol with unspecified color.
    static let chart: Self = .symbol(.chart)
    /// Orbit `chat` icon symbol with unspecified color.
    static let chat: Self = .symbol(.chat)
    /// Orbit `check` icon symbol with unspecified color.
    static let check: Self = .symbol(.check)
    /// Orbit `checkCircle` icon symbol with unspecified color.
    static let checkCircle: Self = .symbol(.checkCircle)
    /// Orbit `chevronDoubleLeft` icon symbol with unspecified color.
    static let chevronDoubleLeft: Self = .symbol(.chevronDoubleLeft)
    /// Orbit `chevronDoubleRight` icon symbol with unspecified color.
    static let chevronDoubleRight: Self = .symbol(.chevronDoubleRight)
    /// Orbit `chevronDown` icon symbol with unspecified color.
    static let chevronDown: Self = .symbol(.chevronDown)
    /// Orbit `chevronLeft` icon symbol with unspecified color.
    static let chevronLeft: Self = .symbol(.chevronLeft)
    /// Orbit `chevronRight` icon symbol with unspecified color.
    static let chevronRight: Self = .symbol(.chevronRight)
    /// Orbit `chevronUp` icon symbol with unspecified color.
    static let chevronUp: Self = .symbol(.chevronUp)
    /// Orbit `child` icon symbol with unspecified color.
    static let child: Self = .symbol(.child)
    /// Orbit `childFriendly` icon symbol with unspecified color.
    static let childFriendly: Self = .symbol(.childFriendly)
    /// Orbit `circle` icon symbol with unspecified color.
    static let circle: Self = .symbol(.circle)
    /// Orbit `circleEmpty` icon symbol with unspecified color.
    static let circleEmpty: Self = .symbol(.circleEmpty)
    /// Orbit `circleFilled` icon symbol with unspecified color.
    static let circleFilled: Self = .symbol(.circleFilled)
    /// Orbit `circleSmall` icon symbol with unspecified color.
    static let circleSmall: Self = .symbol(.circleSmall)
    /// Orbit `circleSmallEmpty` icon symbol with unspecified color.
    static let circleSmallEmpty: Self = .symbol(.circleSmallEmpty)
    /// Orbit `city` icon symbol with unspecified color.
    static let city: Self = .symbol(.city)
    /// Orbit `clock` icon symbol with unspecified color.
    static let clock: Self = .symbol(.clock)
    /// Orbit `close` icon symbol with unspecified color.
    static let close: Self = .symbol(.close)
    /// Orbit `closeCircle` icon symbol with unspecified color.
    static let closeCircle: Self = .symbol(.closeCircle)
    /// Orbit `cocktail` icon symbol with unspecified color.
    static let cocktail: Self = .symbol(.cocktail)
    /// Orbit `code` icon symbol with unspecified color.
    static let code: Self = .symbol(.code)
    /// Orbit `code.kiwi` icon symbol with unspecified color.
    static let codeKiwi: Self = .symbol(.codeKiwi)
    /// Orbit `coffee` icon symbol with unspecified color.
    static let coffee: Self = .symbol(.coffee)
    /// Orbit `colorPicker` icon symbol with unspecified color.
    static let colorPicker: Self = .symbol(.colorPicker)
    /// Orbit `coloredFacebook` icon symbol with unspecified color.
    static let coloredFacebook: Self = .symbol(.coloredFacebook)
    /// Orbit `coloredImessage` icon symbol with unspecified color.
    static let coloredImessage: Self = .symbol(.coloredImessage)
    /// Orbit `coloredMessenger` icon symbol with unspecified color.
    static let coloredMessenger: Self = .symbol(.coloredMessenger)
    /// Orbit `coloredSignal` icon symbol with unspecified color.
    static let coloredSignal: Self = .symbol(.coloredSignal)
    /// Orbit `coloredTelegram` icon symbol with unspecified color.
    static let coloredTelegram: Self = .symbol(.coloredTelegram)
    /// Orbit `coloredTwitter` icon symbol with unspecified color.
    static let coloredTwitter: Self = .symbol(.coloredTwitter)
    /// Orbit `coloredViber` icon symbol with unspecified color.
    static let coloredViber: Self = .symbol(.coloredViber)
    /// Orbit `coloredWhatsapp` icon symbol with unspecified color.
    static let coloredWhatsapp: Self = .symbol(.coloredWhatsapp)
    /// Orbit `compare` icon symbol with unspecified color.
    static let compare: Self = .symbol(.compare)
    /// Orbit `compass` icon symbol with unspecified color.
    static let compass: Self = .symbol(.compass)
    /// Orbit `contactEmail` icon symbol with unspecified color.
    static let contactEmail: Self = .symbol(.contactEmail)
    /// Orbit `creditCard` icon symbol with unspecified color.
    static let creditCard: Self = .symbol(.creditCard)
    /// Orbit `customerSupport` icon symbol with unspecified color.
    static let customerSupport: Self = .symbol(.customerSupport)
    /// Orbit `dashboard` icon symbol with unspecified color.
    static let dashboard: Self = .symbol(.dashboard)
    /// Orbit `deals` icon symbol with unspecified color.
    static let deals: Self = .symbol(.deals)
    /// Orbit `dealsV2` icon symbol with unspecified color.
    static let dealsV2: Self = .symbol(.dealsV2)
    /// Orbit `deviceDesktop` icon symbol with unspecified color.
    static let deviceDesktop: Self = .symbol(.deviceDesktop)
    /// Orbit `deviceMobile` icon symbol with unspecified color.
    static let deviceMobile: Self = .symbol(.deviceMobile)
    /// Orbit `diamond` icon symbol with unspecified color.
    static let diamond: Self = .symbol(.diamond)
    /// Orbit `document` icon symbol with unspecified color.
    static let document: Self = .symbol(.document)
    /// Orbit `download` icon symbol with unspecified color.
    static let download: Self = .symbol(.download)
    /// Orbit `duplicate` icon symbol with unspecified color.
    static let duplicate: Self = .symbol(.duplicate)
    /// Orbit `edit` icon symbol with unspecified color.
    static let edit: Self = .symbol(.edit)
    /// Orbit `editOff` icon symbol with unspecified color.
    static let editOff: Self = .symbol(.editOff)
    /// Orbit `email` icon symbol with unspecified color.
    static let email: Self = .symbol(.email)
    /// Orbit `entertainment` icon symbol with unspecified color.
    static let entertainment: Self = .symbol(.entertainment)
    /// Orbit `exchange` icon symbol with unspecified color.
    static let exchange: Self = .symbol(.exchange)
    /// Orbit `facebook` icon symbol with unspecified color.
    static let facebook: Self = .symbol(.facebook)
    /// Orbit `familyAll` icon symbol with unspecified color.
    static let familyAll: Self = .symbol(.familyAll)
    /// Orbit `familyHalf` icon symbol with unspecified color.
    static let familyHalf: Self = .symbol(.familyHalf)
    /// Orbit `feedback` icon symbol with unspecified color.
    static let feedback: Self = .symbol(.feedback)
    /// Orbit `filters` icon symbol with unspecified color.
    static let filters: Self = .symbol(.filters)
    /// Orbit `flash` icon symbol with unspecified color.
    static let flash: Self = .symbol(.flash)
    /// Orbit `flightDirect` icon symbol with unspecified color.
    static let flightDirect: Self = .symbol(.flightDirect)
    /// Orbit `flightMulticity` icon symbol with unspecified color.
    static let flightMulticity: Self = .symbol(.flightMulticity)
    /// Orbit `flightNomad` icon symbol with unspecified color.
    static let flightNomad: Self = .symbol(.flightNomad)
    /// Orbit `flightReturn` icon symbol with unspecified color.
    static let flightReturn: Self = .symbol(.flightReturn)
    /// Orbit `flightServices` icon symbol with unspecified color.
    static let flightServices: Self = .symbol(.flightServices)
    /// Orbit `fuel` icon symbol with unspecified color.
    static let fuel: Self = .symbol(.fuel)
    /// Orbit `fullScreen` icon symbol with unspecified color.
    static let fullScreen: Self = .symbol(.fullScreen)
    /// Orbit `fullScreenOff` icon symbol with unspecified color.
    static let fullScreenOff: Self = .symbol(.fullScreenOff)
    /// Orbit `gallery` icon symbol with unspecified color.
    static let gallery: Self = .symbol(.gallery)
    /// Orbit `genderMan` icon symbol with unspecified color.
    static let genderMan: Self = .symbol(.genderMan)
    /// Orbit `genderWoman` icon symbol with unspecified color.
    static let genderWoman: Self = .symbol(.genderWoman)
    /// Orbit `github` icon symbol with unspecified color.
    static let github: Self = .symbol(.github)
    /// Orbit `google` icon symbol with unspecified color.
    static let google: Self = .symbol(.google)
    /// Orbit `googlePlay` icon symbol with unspecified color.
    static let googlePlay: Self = .symbol(.googlePlay)
    /// Orbit `gpsFixed` icon symbol with unspecified color.
    static let gpsFixed: Self = .symbol(.gpsFixed)
    /// Orbit `gpsIos` icon symbol with unspecified color.
    static let gpsIos: Self = .symbol(.gpsIos)
    /// Orbit `gpsNotFixed` icon symbol with unspecified color.
    static let gpsNotFixed: Self = .symbol(.gpsNotFixed)
    /// Orbit `gpsOff` icon symbol with unspecified color.
    static let gpsOff: Self = .symbol(.gpsOff)
    /// Orbit `grid` icon symbol with unspecified color.
    static let grid: Self = .symbol(.grid)
    /// Orbit `gym` icon symbol with unspecified color.
    static let gym: Self = .symbol(.gym)
    /// Orbit `history` icon symbol with unspecified color.
    static let history: Self = .symbol(.history)
    /// Orbit `inbox` icon symbol with unspecified color.
    static let inbox: Self = .symbol(.inbox)
    /// Orbit `infant` icon symbol with unspecified color.
    static let infant: Self = .symbol(.infant)
    /// Orbit `informationCircle` icon symbol with unspecified color.
    static let informationCircle: Self = .symbol(.informationCircle)
    /// Orbit `instagram` icon symbol with unspecified color.
    static let instagram: Self = .symbol(.instagram)
    /// Orbit `insurance` icon symbol with unspecified color.
    static let insurance: Self = .symbol(.insurance)
    /// Orbit `insuranceConfirmed` icon symbol with unspecified color.
    static let insuranceConfirmed: Self = .symbol(.insuranceConfirmed)
    /// Orbit `insuranceOff` icon symbol with unspecified color.
    static let insuranceOff: Self = .symbol(.insuranceOff)
    /// Orbit `invoice` icon symbol with unspecified color.
    static let invoice: Self = .symbol(.invoice)
    /// Orbit `itemCompleted` icon symbol with unspecified color.
    static let itemCompleted: Self = .symbol(.itemCompleted)
    /// Orbit `kiwicom` icon symbol with unspecified color.
    static let kiwicom: Self = .symbol(.kiwicom)
    /// Orbit `kiwicomCare` icon symbol with unspecified color.
    static let kiwicomCare: Self = .symbol(.kiwicomCare)
    /// Orbit `kiwicomGuarantee` icon symbol with unspecified color.
    static let kiwicomGuarantee: Self = .symbol(.kiwicomGuarantee)
    /// Orbit `kiwicomNoGuarantee` icon symbol with unspecified color.
    static let kiwicomNoGuarantee: Self = .symbol(.kiwicomNoGuarantee)
    /// Orbit `leisure` icon symbol with unspecified color.
    static let leisure: Self = .symbol(.leisure)
    /// Orbit `link` icon symbol with unspecified color.
    static let link: Self = .symbol(.link)
    /// Orbit `linkedin` icon symbol with unspecified color.
    static let linkedin: Self = .symbol(.linkedin)
    /// Orbit `list` icon symbol with unspecified color.
    static let list: Self = .symbol(.list)
    /// Orbit `location` icon symbol with unspecified color.
    static let location: Self = .symbol(.location)
    /// Orbit `locationA` icon symbol with unspecified color.
    static let locationA: Self = .symbol(.locationA)
    /// Orbit `locationAdd` icon symbol with unspecified color.
    static let locationAdd: Self = .symbol(.locationAdd)
    /// Orbit `locationB` icon symbol with unspecified color.
    static let locationB: Self = .symbol(.locationB)
    /// Orbit `locationC` icon symbol with unspecified color.
    static let locationC: Self = .symbol(.locationC)
    /// Orbit `locationD` icon symbol with unspecified color.
    static let locationD: Self = .symbol(.locationD)
    /// Orbit `locationE` icon symbol with unspecified color.
    static let locationE: Self = .symbol(.locationE)
    /// Orbit `locationF` icon symbol with unspecified color.
    static let locationF: Self = .symbol(.locationF)
    /// Orbit `locationG` icon symbol with unspecified color.
    static let locationG: Self = .symbol(.locationG)
    /// Orbit `locationH` icon symbol with unspecified color.
    static let locationH: Self = .symbol(.locationH)
    /// Orbit `locationI` icon symbol with unspecified color.
    static let locationI: Self = .symbol(.locationI)
    /// Orbit `locationJ` icon symbol with unspecified color.
    static let locationJ: Self = .symbol(.locationJ)
    /// Orbit `lock` icon symbol with unspecified color.
    static let lock: Self = .symbol(.lock)
    /// Orbit `lockOpen` icon symbol with unspecified color.
    static let lockOpen: Self = .symbol(.lockOpen)
    /// Orbit `logout` icon symbol with unspecified color.
    static let logout: Self = .symbol(.logout)
    /// Orbit `lounge` icon symbol with unspecified color.
    static let lounge: Self = .symbol(.lounge)
    /// Orbit `map` icon symbol with unspecified color.
    static let map: Self = .symbol(.map)
    /// Orbit `markdown` icon symbol with unspecified color.
    static let markdown: Self = .symbol(.markdown)
    /// Orbit `meal` icon symbol with unspecified color.
    static let meal: Self = .symbol(.meal)
    /// Orbit `menuHamburger` icon symbol with unspecified color.
    static let menuHamburger: Self = .symbol(.menuHamburger)
    /// Orbit `menuKebab` icon symbol with unspecified color.
    static let menuKebab: Self = .symbol(.menuKebab)
    /// Orbit `menuMeatballs` icon symbol with unspecified color.
    static let menuMeatballs: Self = .symbol(.menuMeatballs)
    /// Orbit `messages` icon symbol with unspecified color.
    static let messages: Self = .symbol(.messages)
    /// Orbit `messagesOutline` icon symbol with unspecified color.
    static let messagesOutline: Self = .symbol(.messagesOutline)
    /// Orbit `minus` icon symbol with unspecified color.
    static let minus: Self = .symbol(.minus)
    /// Orbit `minusCircle` icon symbol with unspecified color.
    static let minusCircle: Self = .symbol(.minusCircle)
    /// Orbit `money` icon symbol with unspecified color.
    static let money: Self = .symbol(.money)
    /// Orbit `moneyTransferIn` icon symbol with unspecified color.
    static let moneyTransferIn: Self = .symbol(.moneyTransferIn)
    /// Orbit `moneyTransferOut` icon symbol with unspecified color.
    static let moneyTransferOut: Self = .symbol(.moneyTransferOut)
    /// Orbit `moon` icon symbol with unspecified color.
    static let moon: Self = .symbol(.moon)
    /// Orbit `musicalInstruments` icon symbol with unspecified color.
    static let musicalInstruments: Self = .symbol(.musicalInstruments)
    /// Orbit `newWindow` icon symbol with unspecified color.
    static let newWindow: Self = .symbol(.newWindow)
    /// Orbit `noFlash` icon symbol with unspecified color.
    static let noFlash: Self = .symbol(.noFlash)
    /// Orbit `noRefund` icon symbol with unspecified color.
    static let noRefund: Self = .symbol(.noRefund)
    /// Orbit `noRescheduling` icon symbol with unspecified color.
    static let noRescheduling: Self = .symbol(.noRescheduling)
    /// Orbit `nonstop` icon symbol with unspecified color.
    static let nonstop: Self = .symbol(.nonstop)
    /// Orbit `notification` icon symbol with unspecified color.
    static let notification: Self = .symbol(.notification)
    /// Orbit `notificationAdd` icon symbol with unspecified color.
    static let notificationAdd: Self = .symbol(.notificationAdd)
    /// Orbit `notificationOff` icon symbol with unspecified color.
    static let notificationOff: Self = .symbol(.notificationOff)
    /// Orbit `notificationOn` icon symbol with unspecified color.
    static let notificationOn: Self = .symbol(.notificationOn)
    /// Orbit `onlineCheckin` icon symbol with unspecified color.
    static let onlineCheckin: Self = .symbol(.onlineCheckin)
    /// Orbit `onlineCheckinOff` icon symbol with unspecified color.
    static let onlineCheckinOff: Self = .symbol(.onlineCheckinOff)
    /// Orbit `outlook` icon symbol with unspecified color.
    static let outlook: Self = .symbol(.outlook)
    /// Orbit `paid` icon symbol with unspecified color.
    static let paid: Self = .symbol(.paid)
    /// Orbit `parking` icon symbol with unspecified color.
    static let parking: Self = .symbol(.parking)
    /// Orbit `partners` icon symbol with unspecified color.
    static let partners: Self = .symbol(.partners)
    /// Orbit `passenger` icon symbol with unspecified color.
    static let passenger: Self = .symbol(.passenger)
    /// Orbit `passengerAdd` icon symbol with unspecified color.
    static let passengerAdd: Self = .symbol(.passengerAdd)
    /// Orbit `passengerOutline` icon symbol with unspecified color.
    static let passengerOutline: Self = .symbol(.passengerOutline)
    /// Orbit `passengerRemove` icon symbol with unspecified color.
    static let passengerRemove: Self = .symbol(.passengerRemove)
    /// Orbit `passengers` icon symbol with unspecified color.
    static let passengers: Self = .symbol(.passengers)
    /// Orbit `passport` icon symbol with unspecified color.
    static let passport: Self = .symbol(.passport)
    /// Orbit `pet` icon symbol with unspecified color.
    static let pet: Self = .symbol(.pet)
    /// Orbit `pharmacy` icon symbol with unspecified color.
    static let pharmacy: Self = .symbol(.pharmacy)
    /// Orbit `phone` icon symbol with unspecified color.
    static let phone: Self = .symbol(.phone)
    /// Orbit `placeholder` icon symbol with unspecified color.
    static let placeholder: Self = .symbol(.placeholder)
    /// Orbit `playground` icon symbol with unspecified color.
    static let playground: Self = .symbol(.playground)
    /// Orbit `plus` icon symbol with unspecified color.
    static let plus: Self = .symbol(.plus)
    /// Orbit `plusCircle` icon symbol with unspecified color.
    static let plusCircle: Self = .symbol(.plusCircle)
    /// Orbit `plusMinus` icon symbol with unspecified color.
    static let plusMinus: Self = .symbol(.plusMinus)
    /// Orbit `pool` icon symbol with unspecified color.
    static let pool: Self = .symbol(.pool)
    /// Orbit `powerPlug` icon symbol with unspecified color.
    static let powerPlug: Self = .symbol(.powerPlug)
    /// Orbit `powerPlugOff` icon symbol with unspecified color.
    static let powerPlugOff: Self = .symbol(.powerPlugOff)
    /// Orbit `priorityBoarding` icon symbol with unspecified color.
    static let priorityBoarding: Self = .symbol(.priorityBoarding)
    /// Orbit `profit` icon symbol with unspecified color.
    static let profit: Self = .symbol(.profit)
    /// Orbit `promoCode` icon symbol with unspecified color.
    static let promoCode: Self = .symbol(.promoCode)
    /// Orbit `qrCode` icon symbol with unspecified color.
    static let qrCode: Self = .symbol(.qrCode)
    /// Orbit `questionCircle` icon symbol with unspecified color.
    static let questionCircle: Self = .symbol(.questionCircle)
    /// Orbit `radar` icon symbol with unspecified color.
    static let radar: Self = .symbol(.radar)
    /// Orbit `radiusSearch` icon symbol with unspecified color.
    static let radiusSearch: Self = .symbol(.radiusSearch)
    /// Orbit `refund` icon symbol with unspecified color.
    static let refund: Self = .symbol(.refund)
    /// Orbit `relax` icon symbol with unspecified color.
    static let relax: Self = .symbol(.relax)
    /// Orbit `reload` icon symbol with unspecified color.
    static let reload: Self = .symbol(.reload)
    /// Orbit `remove` icon symbol with unspecified color.
    static let remove: Self = .symbol(.remove)
    /// Orbit `replace` icon symbol with unspecified color.
    static let replace: Self = .symbol(.replace)
    /// Orbit `restaurant` icon symbol with unspecified color.
    static let restaurant: Self = .symbol(.restaurant)
    /// Orbit `routeNoStops` icon symbol with unspecified color.
    static let routeNoStops: Self = .symbol(.routeNoStops)
    /// Orbit `routeOneStop` icon symbol with unspecified color.
    static let routeOneStop: Self = .symbol(.routeOneStop)
    /// Orbit `routeTwoStops` icon symbol with unspecified color.
    static let routeTwoStops: Self = .symbol(.routeTwoStops)
    /// Orbit `search` icon symbol with unspecified color.
    static let search: Self = .symbol(.search)
    /// Orbit `seat` icon symbol with unspecified color.
    static let seat: Self = .symbol(.seat)
    /// Orbit `seatAisle` icon symbol with unspecified color.
    static let seatAisle: Self = .symbol(.seatAisle)
    /// Orbit `seatExtraLegroom` icon symbol with unspecified color.
    static let seatExtraLegroom: Self = .symbol(.seatExtraLegroom)
    /// Orbit `seatWindow` icon symbol with unspecified color.
    static let seatWindow: Self = .symbol(.seatWindow)
    /// Orbit `security` icon symbol with unspecified color.
    static let security: Self = .symbol(.security)
    /// Orbit `selfTransfer` icon symbol with unspecified color.
    static let selfTransfer: Self = .symbol(.selfTransfer)
    /// Orbit `send` icon symbol with unspecified color.
    static let send: Self = .symbol(.send)
    /// Orbit `settings` icon symbol with unspecified color.
    static let settings: Self = .symbol(.settings)
    /// Orbit `share` icon symbol with unspecified color.
    static let share: Self = .symbol(.share)
    /// Orbit `shareAndroid` icon symbol with unspecified color.
    static let shareAndroid: Self = .symbol(.shareAndroid)
    /// Orbit `shareIos` icon symbol with unspecified color.
    static let shareIos: Self = .symbol(.shareIos)
    /// Orbit `shopping` icon symbol with unspecified color.
    static let shopping: Self = .symbol(.shopping)
    /// Orbit `showLess` icon symbol with unspecified color.
    static let showLess: Self = .symbol(.showLess)
    /// Orbit `showMore` icon symbol with unspecified color.
    static let showMore: Self = .symbol(.showMore)
    /// Orbit `sightseeing` icon symbol with unspecified color.
    static let sightseeing: Self = .symbol(.sightseeing)
    /// Orbit `sign` icon symbol with unspecified color.
    static let sign: Self = .symbol(.sign)
    /// Orbit `smoking` icon symbol with unspecified color.
    static let smoking: Self = .symbol(.smoking)
    /// Orbit `smokingOff` icon symbol with unspecified color.
    static let smokingOff: Self = .symbol(.smokingOff)
    /// Orbit `sms` icon symbol with unspecified color.
    static let sms: Self = .symbol(.sms)
    /// Orbit `sort` icon symbol with unspecified color.
    static let sort: Self = .symbol(.sort)
    /// Orbit `spa` icon symbol with unspecified color.
    static let spa: Self = .symbol(.spa)
    /// Orbit `sportEquipment` icon symbol with unspecified color.
    static let sportEquipment: Self = .symbol(.sportEquipment)
    /// Orbit `sports` icon symbol with unspecified color.
    static let sports: Self = .symbol(.sports)
    /// Orbit `stackoverflow` icon symbol with unspecified color.
    static let stackoverflow: Self = .symbol(.stackoverflow)
    /// Orbit `starEmpty` icon symbol with unspecified color.
    static let starEmpty: Self = .symbol(.starEmpty)
    /// Orbit `starFull` icon symbol with unspecified color.
    static let starFull: Self = .symbol(.starFull)
    /// Orbit `subway` icon symbol with unspecified color.
    static let subway: Self = .symbol(.subway)
    /// Orbit `suitcase` icon symbol with unspecified color.
    static let suitcase: Self = .symbol(.suitcase)
    /// Orbit `sun` icon symbol with unspecified color.
    static let sun: Self = .symbol(.sun)
    /// Orbit `sunrise` icon symbol with unspecified color.
    static let sunrise: Self = .symbol(.sunrise)
    /// Orbit `taxi` icon symbol with unspecified color.
    static let taxi: Self = .symbol(.taxi)
    /// Orbit `terminal` icon symbol with unspecified color.
    static let terminal: Self = .symbol(.terminal)
    /// Orbit `termsAndConditions` icon symbol with unspecified color.
    static let termsAndConditions: Self = .symbol(.termsAndConditions)
    /// Orbit `thumbDown` icon symbol with unspecified color.
    static let thumbDown: Self = .symbol(.thumbDown)
    /// Orbit `thumbUp` icon symbol with unspecified color.
    static let thumbUp: Self = .symbol(.thumbUp)
    /// Orbit `ticket` icon symbol with unspecified color.
    static let ticket: Self = .symbol(.ticket)
    /// Orbit `ticketOutline` icon symbol with unspecified color.
    static let ticketOutline: Self = .symbol(.ticketOutline)
    /// Orbit `timelapse` icon symbol with unspecified color.
    static let timelapse: Self = .symbol(.timelapse)
    /// Orbit `timer` icon symbol with unspecified color.
    static let timer: Self = .symbol(.timer)
    /// Orbit `tips` icon symbol with unspecified color.
    static let tips: Self = .symbol(.tips)
    /// Orbit `toilets` icon symbol with unspecified color.
    static let toilets: Self = .symbol(.toilets)
    /// Orbit `train` icon symbol with unspecified color.
    static let train: Self = .symbol(.train)
    /// Orbit `transmission` icon symbol with unspecified color.
    static let transmission: Self = .symbol(.transmission)
    /// Orbit `trip` icon symbol with unspecified color.
    static let trip: Self = .symbol(.trip)
    /// Orbit `twitter` icon symbol with unspecified color.
    static let twitter: Self = .symbol(.twitter)
    /// Orbit `uber` icon symbol with unspecified color.
    static let uber: Self = .symbol(.uber)
    /// Orbit `upload` icon symbol with unspecified color.
    static let upload: Self = .symbol(.upload)
    /// Orbit `userGroup` icon symbol with unspecified color.
    static let userGroup: Self = .symbol(.userGroup)
    /// Orbit `visa` icon symbol with unspecified color.
    static let visa: Self = .symbol(.visa)
    /// Orbit `visibility` icon symbol with unspecified color.
    static let visibility: Self = .symbol(.visibility)
    /// Orbit `visibilityOff` icon symbol with unspecified color.
    static let visibilityOff: Self = .symbol(.visibilityOff)
    /// Orbit `walk` icon symbol with unspecified color.
    static let walk: Self = .symbol(.walk)
    /// Orbit `wallet` icon symbol with unspecified color.
    static let wallet: Self = .symbol(.wallet)
    /// Orbit `wheelchair` icon symbol with unspecified color.
    static let wheelchair: Self = .symbol(.wheelchair)
    /// Orbit `wifi` icon symbol with unspecified color.
    static let wifi: Self = .symbol(.wifi)
    /// Orbit `wifiOff` icon symbol with unspecified color.
    static let wifiOff: Self = .symbol(.wifiOff)
    /// Orbit `youtube` icon symbol with unspecified color.
    static let youtube: Self = .symbol(.youtube)
}
