
// Generated by 'Automation/update_icons.py'
public extension Icon {

    enum Symbol: CaseIterable, Equatable {
        /// Orbit `accommodation` icon symbol.
        case accommodation
        /// Orbit `accountCircle` icon symbol.
        case accountCircle
        /// Orbit `admin` icon symbol.
        case admin
        /// Orbit `ai` icon symbol.
        case ai
        /// Orbit `airConditioning` icon symbol.
        case airConditioning
        /// Orbit `airplane` icon symbol.
        case airplane
        /// Orbit `airplaneDown` icon symbol.
        case airplaneDown
        /// Orbit `airplaneLanding` icon symbol.
        case airplaneLanding
        /// Orbit `airplaneReturn` icon symbol.
        case airplaneReturn
        /// Orbit `airplaneTakeoff` icon symbol.
        case airplaneTakeoff
        /// Orbit `airplaneUp` icon symbol.
        case airplaneUp
        /// Orbit `airplaneUpOff` icon symbol.
        case airplaneUpOff
        /// Orbit `airportSecurity` icon symbol.
        case airportSecurity
        /// Orbit `alert` icon symbol.
        case alert
        /// Orbit `alertCircle` icon symbol.
        case alertCircle
        /// Orbit `alertOctagon` icon symbol.
        case alertOctagon
        /// Orbit `all` icon symbol.
        case all
        /// Orbit `android` icon symbol.
        case android
        /// Orbit `anywhere` icon symbol.
        case anywhere
        /// Orbit `appNotification` icon symbol.
        case appNotification
        /// Orbit `apple` icon symbol.
        case apple
        /// Orbit `arrowDown` icon symbol.
        case arrowDown
        /// Orbit `arrowUp` icon symbol.
        case arrowUp
        /// Orbit `atm` icon symbol.
        case atm
        /// Orbit `attachment` icon symbol.
        case attachment
        /// Orbit `baggageCabin` icon symbol.
        case baggageCabin
        /// Orbit `baggageCabinLight` icon symbol.
        case baggageCabinLight
        /// Orbit `baggageCabinNone` icon symbol.
        case baggageCabinNone
        /// Orbit `baggageCabinNoneLight` icon symbol.
        case baggageCabinNoneLight
        /// Orbit `baggageChecked10` icon symbol.
        case baggageChecked10
        /// Orbit `baggageChecked10Light` icon symbol.
        case baggageChecked10Light
        /// Orbit `baggageChecked20` icon symbol.
        case baggageChecked20
        /// Orbit `baggageChecked20Light` icon symbol.
        case baggageChecked20Light
        /// Orbit `baggageChecked30` icon symbol.
        case baggageChecked30
        /// Orbit `baggageChecked30Light` icon symbol.
        case baggageChecked30Light
        /// Orbit `baggageCheckedNone` icon symbol.
        case baggageCheckedNone
        /// Orbit `baggageCheckedNoneLight` icon symbol.
        case baggageCheckedNoneLight
        /// Orbit `baggagePersonal` icon symbol.
        case baggagePersonal
        /// Orbit `baggagePersonalLight` icon symbol.
        case baggagePersonalLight
        /// Orbit `baggagePersonalNone` icon symbol.
        case baggagePersonalNone
        /// Orbit `baggagePersonalNoneLight` icon symbol.
        case baggagePersonalNoneLight
        /// Orbit `baggageRecheck` icon symbol.
        case baggageRecheck
        /// Orbit `baggageSet` icon symbol.
        case baggageSet
        /// Orbit `baggageSetLight` icon symbol.
        case baggageSetLight
        /// Orbit `baggageStorage` icon symbol.
        case baggageStorage
        /// Orbit `bank` icon symbol.
        case bank
        /// Orbit `billingDetails` icon symbol.
        case billingDetails
        /// Orbit `boardingGate` icon symbol.
        case boardingGate
        /// Orbit `boat` icon symbol.
        case boat
        /// Orbit `bookmark` icon symbol.
        case bookmark
        /// Orbit `bug` icon symbol.
        case bug
        /// Orbit `bus` icon symbol.
        case bus
        /// Orbit `cake` icon symbol.
        case cake
        /// Orbit `calendar` icon symbol.
        case calendar
        /// Orbit `calendarAnytime` icon symbol.
        case calendarAnytime
        /// Orbit `calendarDuration` icon symbol.
        case calendarDuration
        /// Orbit `calendarRange` icon symbol.
        case calendarRange
        /// Orbit `calendarTripLength` icon symbol.
        case calendarTripLength
        /// Orbit `camera` icon symbol.
        case camera
        /// Orbit `car` icon symbol.
        case car
        /// Orbit `carDoor` icon symbol.
        case carDoor
        /// Orbit `carRental` icon symbol.
        case carRental
        /// Orbit `chart` icon symbol.
        case chart
        /// Orbit `chat` icon symbol.
        case chat
        /// Orbit `check` icon symbol.
        case check
        /// Orbit `checkCircle` icon symbol.
        case checkCircle
        /// Orbit `chevronBackward` icon symbol.
        case chevronBackward
        /// Orbit `chevronDoubleBackward` icon symbol.
        case chevronDoubleBackward
        /// Orbit `chevronDoubleForward` icon symbol.
        case chevronDoubleForward
        /// Orbit `chevronDown` icon symbol.
        case chevronDown
        /// Orbit `chevronForward` icon symbol.
        case chevronForward
        /// Orbit `chevronUp` icon symbol.
        case chevronUp
        /// Orbit `child` icon symbol.
        case child
        /// Orbit `childFriendly` icon symbol.
        case childFriendly
        /// Orbit `circle` icon symbol.
        case circle
        /// Orbit `circleEmpty` icon symbol.
        case circleEmpty
        /// Orbit `circleFilled` icon symbol.
        case circleFilled
        /// Orbit `circleSmall` icon symbol.
        case circleSmall
        /// Orbit `circleSmallEmpty` icon symbol.
        case circleSmallEmpty
        /// Orbit `city` icon symbol.
        case city
        /// Orbit `clock` icon symbol.
        case clock
        /// Orbit `close` icon symbol.
        case close
        /// Orbit `closeCircle` icon symbol.
        case closeCircle
        /// Orbit `cocktail` icon symbol.
        case cocktail
        /// Orbit `code` icon symbol.
        case code
        /// Orbit `code.kiwi` icon symbol.
        case codeKiwi
        /// Orbit `coffee` icon symbol.
        case coffee
        /// Orbit `colorPicker` icon symbol.
        case colorPicker
        /// Orbit `coloredFacebook` icon symbol.
        case coloredFacebook
        /// Orbit `coloredImessage` icon symbol.
        case coloredImessage
        /// Orbit `coloredMessenger` icon symbol.
        case coloredMessenger
        /// Orbit `coloredSignal` icon symbol.
        case coloredSignal
        /// Orbit `coloredTelegram` icon symbol.
        case coloredTelegram
        /// Orbit `coloredTwitter` icon symbol.
        case coloredTwitter
        /// Orbit `coloredViber` icon symbol.
        case coloredViber
        /// Orbit `coloredWhatsapp` icon symbol.
        case coloredWhatsapp
        /// Orbit `compare` icon symbol.
        case compare
        /// Orbit `compass` icon symbol.
        case compass
        /// Orbit `contactEmail` icon symbol.
        case contactEmail
        /// Orbit `copy` icon symbol.
        case copy
        /// Orbit `creditCard` icon symbol.
        case creditCard
        /// Orbit `customerSupport` icon symbol.
        case customerSupport
        /// Orbit `dashboard` icon symbol.
        case dashboard
        /// Orbit `deals` icon symbol.
        case deals
        /// Orbit `dealsV2` icon symbol.
        case dealsV2
        /// Orbit `deviceDesktop` icon symbol.
        case deviceDesktop
        /// Orbit `deviceMobile` icon symbol.
        case deviceMobile
        /// Orbit `diamond` icon symbol.
        case diamond
        /// Orbit `document` icon symbol.
        case document
        /// Orbit `download` icon symbol.
        case download
        /// Orbit `duplicate` icon symbol.
        case duplicate
        /// Orbit `edit` icon symbol.
        case edit
        /// Orbit `editOff` icon symbol.
        case editOff
        /// Orbit `email` icon symbol.
        case email
        /// Orbit `entertainment` icon symbol.
        case entertainment
        /// Orbit `exchange` icon symbol.
        case exchange
        /// Orbit `facebook` icon symbol.
        case facebook
        /// Orbit `familyAll` icon symbol.
        case familyAll
        /// Orbit `familyHalf` icon symbol.
        case familyHalf
        /// Orbit `feedback` icon symbol.
        case feedback
        /// Orbit `filters` icon symbol.
        case filters
        /// Orbit `flash` icon symbol.
        case flash
        /// Orbit `flightDirect` icon symbol.
        case flightDirect
        /// Orbit `flightMulticity` icon symbol.
        case flightMulticity
        /// Orbit `flightNomad` icon symbol.
        case flightNomad
        /// Orbit `flightReturn` icon symbol.
        case flightReturn
        /// Orbit `flightServices` icon symbol.
        case flightServices
        /// Orbit `fuel` icon symbol.
        case fuel
        /// Orbit `fullScreen` icon symbol.
        case fullScreen
        /// Orbit `fullScreenOff` icon symbol.
        case fullScreenOff
        /// Orbit `gallery` icon symbol.
        case gallery
        /// Orbit `genderMan` icon symbol.
        case genderMan
        /// Orbit `genderWoman` icon symbol.
        case genderWoman
        /// Orbit `github` icon symbol.
        case github
        /// Orbit `google` icon symbol.
        case google
        /// Orbit `googlePlay` icon symbol.
        case googlePlay
        /// Orbit `gpsFixed` icon symbol.
        case gpsFixed
        /// Orbit `gpsIos` icon symbol.
        case gpsIos
        /// Orbit `gpsNotFixed` icon symbol.
        case gpsNotFixed
        /// Orbit `gpsOff` icon symbol.
        case gpsOff
        /// Orbit `grid` icon symbol.
        case grid
        /// Orbit `gym` icon symbol.
        case gym
        /// Orbit `heart` icon symbol.
        case heart
        /// Orbit `heartOutline` icon symbol.
        case heartOutline
        /// Orbit `history` icon symbol.
        case history
        /// Orbit `inbox` icon symbol.
        case inbox
        /// Orbit `infant` icon symbol.
        case infant
        /// Orbit `informationCircle` icon symbol.
        case informationCircle
        /// Orbit `informationCircleLight` icon symbol.
        case informationCircleLight
        /// Orbit `instagram` icon symbol.
        case instagram
        /// Orbit `insurance` icon symbol.
        case insurance
        /// Orbit `insuranceConfirmed` icon symbol.
        case insuranceConfirmed
        /// Orbit `insuranceOff` icon symbol.
        case insuranceOff
        /// Orbit `invoice` icon symbol.
        case invoice
        /// Orbit `itemCompleted` icon symbol.
        case itemCompleted
        /// Orbit `kiwicom` icon symbol.
        case kiwicom
        /// Orbit `kiwicomCare` icon symbol.
        case kiwicomCare
        /// Orbit `kiwicomGuarantee` icon symbol.
        case kiwicomGuarantee
        /// Orbit `kiwicomNoGuarantee` icon symbol.
        case kiwicomNoGuarantee
        /// Orbit `leisure` icon symbol.
        case leisure
        /// Orbit `link` icon symbol.
        case link
        /// Orbit `linkedin` icon symbol.
        case linkedin
        /// Orbit `list` icon symbol.
        case list
        /// Orbit `location` icon symbol.
        case location
        /// Orbit `locationA` icon symbol.
        case locationA
        /// Orbit `locationAdd` icon symbol.
        case locationAdd
        /// Orbit `locationB` icon symbol.
        case locationB
        /// Orbit `locationC` icon symbol.
        case locationC
        /// Orbit `locationD` icon symbol.
        case locationD
        /// Orbit `locationE` icon symbol.
        case locationE
        /// Orbit `locationF` icon symbol.
        case locationF
        /// Orbit `locationG` icon symbol.
        case locationG
        /// Orbit `locationH` icon symbol.
        case locationH
        /// Orbit `locationI` icon symbol.
        case locationI
        /// Orbit `locationJ` icon symbol.
        case locationJ
        /// Orbit `lock` icon symbol.
        case lock
        /// Orbit `lockOpen` icon symbol.
        case lockOpen
        /// Orbit `logout` icon symbol.
        case logout
        /// Orbit `lounge` icon symbol.
        case lounge
        /// Orbit `map` icon symbol.
        case map
        /// Orbit `markdown` icon symbol.
        case markdown
        /// Orbit `meal` icon symbol.
        case meal
        /// Orbit `menuHamburger` icon symbol.
        case menuHamburger
        /// Orbit `menuKebab` icon symbol.
        case menuKebab
        /// Orbit `menuMeatballs` icon symbol.
        case menuMeatballs
        /// Orbit `messages` icon symbol.
        case messages
        /// Orbit `messagesOutline` icon symbol.
        case messagesOutline
        /// Orbit `minus` icon symbol.
        case minus
        /// Orbit `minusCircle` icon symbol.
        case minusCircle
        /// Orbit `money` icon symbol.
        case money
        /// Orbit `moneyTransferIn` icon symbol.
        case moneyTransferIn
        /// Orbit `moneyTransferOut` icon symbol.
        case moneyTransferOut
        /// Orbit `moon` icon symbol.
        case moon
        /// Orbit `musicalInstruments` icon symbol.
        case musicalInstruments
        /// Orbit `newWindow` icon symbol.
        case newWindow
        /// Orbit `noFlash` icon symbol.
        case noFlash
        /// Orbit `noRefund` icon symbol.
        case noRefund
        /// Orbit `noRescheduling` icon symbol.
        case noRescheduling
        /// Orbit `noWifiLight` icon symbol.
        case noWifiLight
        /// Orbit `nonstop` icon symbol.
        case nonstop
        /// Orbit `notification` icon symbol.
        case notification
        /// Orbit `notificationAdd` icon symbol.
        case notificationAdd
        /// Orbit `notificationOff` icon symbol.
        case notificationOff
        /// Orbit `notificationOn` icon symbol.
        case notificationOn
        /// Orbit `onlineCheckin` icon symbol.
        case onlineCheckin
        /// Orbit `onlineCheckinOff` icon symbol.
        case onlineCheckinOff
        /// Orbit `outlook` icon symbol.
        case outlook
        /// Orbit `paid` icon symbol.
        case paid
        /// Orbit `parking` icon symbol.
        case parking
        /// Orbit `partners` icon symbol.
        case partners
        /// Orbit `passenger` icon symbol.
        case passenger
        /// Orbit `passengerAdd` icon symbol.
        case passengerAdd
        /// Orbit `passengerOutline` icon symbol.
        case passengerOutline
        /// Orbit `passengerRemove` icon symbol.
        case passengerRemove
        /// Orbit `passengers` icon symbol.
        case passengers
        /// Orbit `passport` icon symbol.
        case passport
        /// Orbit `pet` icon symbol.
        case pet
        /// Orbit `pharmacy` icon symbol.
        case pharmacy
        /// Orbit `phone` icon symbol.
        case phone
        /// Orbit `phoneUpdatesLight` icon symbol.
        case phoneUpdatesLight
        /// Orbit `pin` icon symbol.
        case pin
        /// Orbit `pinOutline` icon symbol.
        case pinOutline
        /// Orbit `placeholder` icon symbol.
        case placeholder
        /// Orbit `play` icon symbol.
        case play
        /// Orbit `playground` icon symbol.
        case playground
        /// Orbit `plus` icon symbol.
        case plus
        /// Orbit `plusCircle` icon symbol.
        case plusCircle
        /// Orbit `plusMinus` icon symbol.
        case plusMinus
        /// Orbit `pool` icon symbol.
        case pool
        /// Orbit `powerPlug` icon symbol.
        case powerPlug
        /// Orbit `powerPlugOff` icon symbol.
        case powerPlugOff
        /// Orbit `priceChange` icon symbol.
        case priceChange
        /// Orbit `priorityBoarding` icon symbol.
        case priorityBoarding
        /// Orbit `profit` icon symbol.
        case profit
        /// Orbit `promoCode` icon symbol.
        case promoCode
        /// Orbit `qrCode` icon symbol.
        case qrCode
        /// Orbit `questionCircle` icon symbol.
        case questionCircle
        /// Orbit `radar` icon symbol.
        case radar
        /// Orbit `radiusSearch` icon symbol.
        case radiusSearch
        /// Orbit `rebookingLight` icon symbol.
        case rebookingLight
        /// Orbit `rebookingNoneLight` icon symbol.
        case rebookingNoneLight
        /// Orbit `refund` icon symbol.
        case refund
        /// Orbit `refundLight` icon symbol.
        case refundLight
        /// Orbit `refundNoneLight` icon symbol.
        case refundNoneLight
        /// Orbit `relax` icon symbol.
        case relax
        /// Orbit `reload` icon symbol.
        case reload
        /// Orbit `remove` icon symbol.
        case remove
        /// Orbit `replace` icon symbol.
        case replace
        /// Orbit `restaurant` icon symbol.
        case restaurant
        /// Orbit `routeNoStops` icon symbol.
        case routeNoStops
        /// Orbit `routeOneStop` icon symbol.
        case routeOneStop
        /// Orbit `routeTwoStops` icon symbol.
        case routeTwoStops
        /// Orbit `search` icon symbol.
        case search
        /// Orbit `seat` icon symbol.
        case seat
        /// Orbit `seatAisle` icon symbol.
        case seatAisle
        /// Orbit `seatExtraLegroom` icon symbol.
        case seatExtraLegroom
        /// Orbit `seatLight` icon symbol.
        case seatLight
        /// Orbit `seatWindow` icon symbol.
        case seatWindow
        /// Orbit `security` icon symbol.
        case security
        /// Orbit `selfTransfer` icon symbol.
        case selfTransfer
        /// Orbit `send` icon symbol.
        case send
        /// Orbit `settings` icon symbol.
        case settings
        /// Orbit `share` icon symbol.
        case share
        /// Orbit `shareAndroid` icon symbol.
        case shareAndroid
        /// Orbit `shareAndroidOutline` icon symbol.
        case shareAndroidOutline
        /// Orbit `shareIos` icon symbol.
        case shareIos
        /// Orbit `shopping` icon symbol.
        case shopping
        /// Orbit `showLess` icon symbol.
        case showLess
        /// Orbit `showMore` icon symbol.
        case showMore
        /// Orbit `sightseeing` icon symbol.
        case sightseeing
        /// Orbit `sign` icon symbol.
        case sign
        /// Orbit `smoking` icon symbol.
        case smoking
        /// Orbit `smokingOff` icon symbol.
        case smokingOff
        /// Orbit `sms` icon symbol.
        case sms
        /// Orbit `sort` icon symbol.
        case sort
        /// Orbit `spa` icon symbol.
        case spa
        /// Orbit `sportEquipment` icon symbol.
        case sportEquipment
        /// Orbit `sports` icon symbol.
        case sports
        /// Orbit `stackoverflow` icon symbol.
        case stackoverflow
        /// Orbit `starEmpty` icon symbol.
        case starEmpty
        /// Orbit `starFull` icon symbol.
        case starFull
        /// Orbit `subway` icon symbol.
        case subway
        /// Orbit `suitcase` icon symbol.
        case suitcase
        /// Orbit `sun` icon symbol.
        case sun
        /// Orbit `sunrise` icon symbol.
        case sunrise
        /// Orbit `taxi` icon symbol.
        case taxi
        /// Orbit `terminal` icon symbol.
        case terminal
        /// Orbit `termsAndConditions` icon symbol.
        case termsAndConditions
        /// Orbit `thumbDown` icon symbol.
        case thumbDown
        /// Orbit `thumbUp` icon symbol.
        case thumbUp
        /// Orbit `ticket` icon symbol.
        case ticket
        /// Orbit `ticketOutline` icon symbol.
        case ticketOutline
        /// Orbit `tiktok` icon symbol.
        case tiktok
        /// Orbit `timelapse` icon symbol.
        case timelapse
        /// Orbit `timer` icon symbol.
        case timer
        /// Orbit `tips` icon symbol.
        case tips
        /// Orbit `toilets` icon symbol.
        case toilets
        /// Orbit `train` icon symbol.
        case train
        /// Orbit `transmission` icon symbol.
        case transmission
        /// Orbit `trip` icon symbol.
        case trip
        /// Orbit `tripUpdatesLight` icon symbol.
        case tripUpdatesLight
        /// Orbit `twitter` icon symbol.
        case twitter
        /// Orbit `uber` icon symbol.
        case uber
        /// Orbit `upload` icon symbol.
        case upload
        /// Orbit `userGroup` icon symbol.
        case userGroup
        /// Orbit `visa` icon symbol.
        case visa
        /// Orbit `visibility` icon symbol.
        case visibility
        /// Orbit `visibilityOff` icon symbol.
        case visibilityOff
        /// Orbit `walk` icon symbol.
        case walk
        /// Orbit `wallet` icon symbol.
        case wallet
        /// Orbit `wheelchair` icon symbol.
        case wheelchair
        /// Orbit `wifi` icon symbol.
        case wifi
        /// Orbit `wifiLight` icon symbol.
        case wifiLight
        /// Orbit `wifiOff` icon symbol.
        case wifiOff
        /// Orbit `youtube` icon symbol.
        case youtube

        public var value: String {
            switch self {
                case .accommodation: return "\u{3024}"
                case .accountCircle: return "\u{2008}"
                case .admin: return "\u{3024}"
                case .ai: return "\u{9860}"
                case .airConditioning: return "\u{3024}"
                case .airplane: return "\u{4947}"
                case .airplaneDown: return "\u{2715}"
                case .airplaneLanding: return "\u{3024}"
                case .airplaneReturn: return "\u{5982}"
                case .airplaneTakeoff: return "\u{3024}"
                case .airplaneUp: return "\u{9442}"
                case .airplaneUpOff: return "\u{9310}"
                case .airportSecurity: return "\u{5410}"
                case .alert: return "\u{3024}"
                case .alertCircle: return "\u{3024}"
                case .alertOctagon: return "\u{3024}"
                case .all: return "\u{3671}"
                case .android: return "\u{2402}"
                case .anywhere: return "\u{3751}"
                case .appNotification: return "\u{5083}"
                case .apple: return "\u{1211}"
                case .arrowDown: return "\u{9572}"
                case .arrowUp: return "\u{3024}"
                case .atm: return "\u{3024}"
                case .attachment: return "\u{4440}"
                case .baggageCabin: return "\u{3024}"
                case .baggageCabinLight: return "\u{2521}"
                case .baggageCabinNone: return "\u{3024}"
                case .baggageCabinNoneLight: return "\u{3427}"
                case .baggageChecked10: return "\u{9038}"
                case .baggageChecked10Light: return "\u{9187}"
                case .baggageChecked20: return "\u{3024}"
                case .baggageChecked20Light: return "\u{5988}"
                case .baggageChecked30: return "\u{3024}"
                case .baggageChecked30Light: return "\u{4855}"
                case .baggageCheckedNone: return "\u{2865}"
                case .baggageCheckedNoneLight: return "\u{2193}"
                case .baggagePersonal: return "\u{3024}"
                case .baggagePersonalLight: return "\u{2461}"
                case .baggagePersonalNone: return "\u{3024}"
                case .baggagePersonalNoneLight: return "\u{5115}"
                case .baggageRecheck: return "\u{7766}"
                case .baggageSet: return "\u{8851}"
                case .baggageSetLight: return "\u{3296}"
                case .baggageStorage: return "\u{3024}"
                case .bank: return "\u{6692}"
                case .billingDetails: return "\u{3024}"
                case .boardingGate: return "\u{9372}"
                case .boat: return "\u{3024}"
                case .bookmark: return "\u{9344}"
                case .bug: return "\u{3024}"
                case .bus: return "\u{3024}"
                case .cake: return "\u{4460}"
                case .calendar: return "\u{3024}"
                case .calendarAnytime: return "\u{4527}"
                case .calendarDuration: return "\u{4904}"
                case .calendarRange: return "\u{5952}"
                case .calendarTripLength: return "\u{3556}"
                case .camera: return "\u{2768}"
                case .car: return "\u{3024}"
                case .carDoor: return "\u{3024}"
                case .carRental: return "\u{3024}"
                case .chart: return "\u{6925}"
                case .chat: return "\u{8647}"
                case .check: return "\u{3024}"
                case .checkCircle: return "\u{3024}"
                case .chevronBackward: return "\u{3024}"
                case .chevronDoubleBackward: return "\u{2264}"
                case .chevronDoubleForward: return "\u{7058}"
                case .chevronDown: return "\u{3024}"
                case .chevronForward: return "\u{3024}"
                case .chevronUp: return "\u{3024}"
                case .child: return "\u{3024}"
                case .childFriendly: return "\u{3024}"
                case .circle: return "\u{3024}"
                case .circleEmpty: return "\u{5486}"
                case .circleFilled: return "\u{3024}"
                case .circleSmall: return "\u{8053}"
                case .circleSmallEmpty: return "\u{9571}"
                case .city: return "\u{3024}"
                case .clock: return "\u{8108}"
                case .close: return "\u{3024}"
                case .closeCircle: return "\u{3024}"
                case .cocktail: return "\u{3024}"
                case .code: return "\u{5056}"
                case .codeKiwi: return "\u{5988}"
                case .coffee: return "\u{3024}"
                case .colorPicker: return "\u{8770}"
                case .coloredFacebook: return "\u{2129}"
                case .coloredImessage: return "\u{9052}"
                case .coloredMessenger: return "\u{4407}"
                case .coloredSignal: return "\u{4623}"
                case .coloredTelegram: return "\u{5916}"
                case .coloredTwitter: return "\u{2967}"
                case .coloredViber: return "\u{6059}"
                case .coloredWhatsapp: return "\u{3046}"
                case .compare: return "\u{3024}"
                case .compass: return "\u{4816}"
                case .contactEmail: return "\u{3024}"
                case .copy: return "\u{7844}"
                case .creditCard: return "\u{3024}"
                case .customerSupport: return "\u{3024}"
                case .dashboard: return "\u{1469}"
                case .deals: return "\u{3024}"
                case .dealsV2: return "\u{6728}"
                case .deviceDesktop: return "\u{1774}"
                case .deviceMobile: return "\u{3069}"
                case .diamond: return "\u{8630}"
                case .document: return "\u{3024}"
                case .download: return "\u{3024}"
                case .duplicate: return "\u{9494}"
                case .edit: return "\u{6036}"
                case .editOff: return "\u{3372}"
                case .email: return "\u{3953}"
                case .entertainment: return "\u{2702}"
                case .exchange: return "\u{1707}"
                case .facebook: return "\u{4121}"
                case .familyAll: return "\u{3024}"
                case .familyHalf: return "\u{3024}"
                case .feedback: return "\u{3024}"
                case .filters: return "\u{3024}"
                case .flash: return "\u{9010}"
                case .flightDirect: return "\u{7084}"
                case .flightMulticity: return "\u{7878}"
                case .flightNomad: return "\u{3024}"
                case .flightReturn: return "\u{8043}"
                case .flightServices: return "\u{8447}"
                case .fuel: return "\u{9902}"
                case .fullScreen: return "\u{3024}"
                case .fullScreenOff: return "\u{6821}"
                case .gallery: return "\u{3024}"
                case .genderMan: return "\u{7062}"
                case .genderWoman: return "\u{3024}"
                case .github: return "\u{8955}"
                case .google: return "\u{5959}"
                case .googlePlay: return "\u{1038}"
                case .gpsFixed: return "\u{6683}"
                case .gpsIos: return "\u{8993}"
                case .gpsNotFixed: return "\u{1504}"
                case .gpsOff: return "\u{3024}"
                case .grid: return "\u{5681}"
                case .gym: return "\u{7005}"
                case .heart: return "\u{3456}"
                case .heartOutline: return "\u{3312}"
                case .history: return "\u{3024}"
                case .inbox: return "\u{6431}"
                case .infant: return "\u{9347}"
                case .informationCircle: return "\u{3024}"
                case .informationCircleLight: return "\u{4154}"
                case .instagram: return "\u{7300}"
                case .insurance: return "\u{3024}"
                case .insuranceConfirmed: return "\u{3024}"
                case .insuranceOff: return "\u{4031}"
                case .invoice: return "\u{3024}"
                case .itemCompleted: return "\u{5244}"
                case .kiwicom: return "\u{3024}"
                case .kiwicomCare: return "\u{9753}"
                case .kiwicomGuarantee: return "\u{2319}"
                case .kiwicomNoGuarantee: return "\u{3024}"
                case .leisure: return "\u{8309}"
                case .link: return "\u{9259}"
                case .linkedin: return "\u{9652}"
                case .list: return "\u{7893}"
                case .location: return "\u{9892}"
                case .locationA: return "\u{9233}"
                case .locationAdd: return "\u{6403}"
                case .locationB: return "\u{3024}"
                case .locationC: return "\u{3024}"
                case .locationD: return "\u{3024}"
                case .locationE: return "\u{1680}"
                case .locationF: return "\u{3024}"
                case .locationG: return "\u{3024}"
                case .locationH: return "\u{3445}"
                case .locationI: return "\u{1974}"
                case .locationJ: return "\u{3024}"
                case .lock: return "\u{3024}"
                case .lockOpen: return "\u{3024}"
                case .logout: return "\u{3794}"
                case .lounge: return "\u{3024}"
                case .map: return "\u{3024}"
                case .markdown: return "\u{8187}"
                case .meal: return "\u{3024}"
                case .menuHamburger: return "\u{3024}"
                case .menuKebab: return "\u{6385}"
                case .menuMeatballs: return "\u{7789}"
                case .messages: return "\u{3024}"
                case .messagesOutline: return "\u{9970}"
                case .minus: return "\u{3024}"
                case .minusCircle: return "\u{4552}"
                case .money: return "\u{8910}"
                case .moneyTransferIn: return "\u{9169}"
                case .moneyTransferOut: return "\u{3024}"
                case .moon: return "\u{3024}"
                case .musicalInstruments: return "\u{3024}"
                case .newWindow: return "\u{2101}"
                case .noFlash: return "\u{6933}"
                case .noRefund: return "\u{3024}"
                case .noRescheduling: return "\u{3024}"
                case .noWifiLight: return "\u{4160}"
                case .nonstop: return "\u{3024}"
                case .notification: return "\u{3024}"
                case .notificationAdd: return "\u{9535}"
                case .notificationOff: return "\u{7252}"
                case .notificationOn: return "\u{9742}"
                case .onlineCheckin: return "\u{8410}"
                case .onlineCheckinOff: return "\u{8777}"
                case .outlook: return "\u{5080}"
                case .paid: return "\u{3024}"
                case .parking: return "\u{3024}"
                case .partners: return "\u{3024}"
                case .passenger: return "\u{3024}"
                case .passengerAdd: return "\u{4935}"
                case .passengerOutline: return "\u{6092}"
                case .passengerRemove: return "\u{3024}"
                case .passengers: return "\u{2111}"
                case .passport: return "\u{5491}"
                case .pet: return "\u{3024}"
                case .pharmacy: return "\u{3024}"
                case .phone: return "\u{3024}"
                case .phoneUpdatesLight: return "\u{4160}"
                case .pin: return "\u{3914}"
                case .pinOutline: return "\u{3435}"
                case .placeholder: return "\u{1255}"
                case .play: return "\u{6189}"
                case .playground: return "\u{6111}"
                case .plus: return "\u{3586}"
                case .plusCircle: return "\u{3024}"
                case .plusMinus: return "\u{4217}"
                case .pool: return "\u{9337}"
                case .powerPlug: return "\u{3024}"
                case .powerPlugOff: return "\u{8785}"
                case .priceChange: return "\u{3027}"
                case .priorityBoarding: return "\u{3024}"
                case .profit: return "\u{7636}"
                case .promoCode: return "\u{3024}"
                case .qrCode: return "\u{3024}"
                case .questionCircle: return "\u{3024}"
                case .radar: return "\u{3024}"
                case .radiusSearch: return "\u{3024}"
                case .rebookingLight: return "\u{7002}"
                case .rebookingNoneLight: return "\u{8997}"
                case .refund: return "\u{3024}"
                case .refundLight: return "\u{9565}"
                case .refundNoneLight: return "\u{7572}"
                case .relax: return "\u{9709}"
                case .reload: return "\u{3024}"
                case .remove: return "\u{3024}"
                case .replace: return "\u{9641}"
                case .restaurant: return "\u{8995}"
                case .routeNoStops: return "\u{1734}"
                case .routeOneStop: return "\u{5253}"
                case .routeTwoStops: return "\u{8469}"
                case .search: return "\u{3024}"
                case .seat: return "\u{3024}"
                case .seatAisle: return "\u{2999}"
                case .seatExtraLegroom: return "\u{3024}"
                case .seatLight: return "\u{4998}"
                case .seatWindow: return "\u{9964}"
                case .security: return "\u{8185}"
                case .selfTransfer: return "\u{3024}"
                case .send: return "\u{3024}"
                case .settings: return "\u{3024}"
                case .share: return "\u{9200}"
                case .shareAndroid: return "\u{3024}"
                case .shareAndroidOutline: return "\u{9305}"
                case .shareIos: return "\u{6041}"
                case .shopping: return "\u{3024}"
                case .showLess: return "\u{3024}"
                case .showMore: return "\u{5137}"
                case .sightseeing: return "\u{3309}"
                case .sign: return "\u{3024}"
                case .smoking: return "\u{7198}"
                case .smokingOff: return "\u{4702}"
                case .sms: return "\u{7270}"
                case .sort: return "\u{1188}"
                case .spa: return "\u{3024}"
                case .sportEquipment: return "\u{3024}"
                case .sports: return "\u{3024}"
                case .stackoverflow: return "\u{3239}"
                case .starEmpty: return "\u{3024}"
                case .starFull: return "\u{3024}"
                case .subway: return "\u{7603}"
                case .suitcase: return "\u{3024}"
                case .sun: return "\u{3024}"
                case .sunrise: return "\u{3024}"
                case .taxi: return "\u{1833}"
                case .terminal: return "\u{2165}"
                case .termsAndConditions: return "\u{3024}"
                case .thumbDown: return "\u{4945}"
                case .thumbUp: return "\u{9504}"
                case .ticket: return "\u{3024}"
                case .ticketOutline: return "\u{2476}"
                case .tiktok: return "\u{2167}"
                case .timelapse: return "\u{3024}"
                case .timer: return "\u{2231}"
                case .tips: return "\u{4114}"
                case .toilets: return "\u{7816}"
                case .train: return "\u{1576}"
                case .transmission: return "\u{8486}"
                case .trip: return "\u{3024}"
                case .tripUpdatesLight: return "\u{4160}"
                case .twitter: return "\u{3571}"
                case .uber: return "\u{7053}"
                case .upload: return "\u{3024}"
                case .userGroup: return "\u{3024}"
                case .visa: return "\u{3991}"
                case .visibility: return "\u{7489}"
                case .visibilityOff: return "\u{4122}"
                case .walk: return "\u{8879}"
                case .wallet: return "\u{3772}"
                case .wheelchair: return "\u{3024}"
                case .wifi: return "\u{4322}"
                case .wifiLight: return "\u{4160}"
                case .wifiOff: return "\u{1140}"
                case .youtube: return "\u{7992}"
            }
        }
    }
}
