name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version/tag for this release"
        required: true
      changelog:
        description: "What's new in this release"
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update assets
        run: |
          ./Automation/update_illustrations.py
          ./Automation/update_colors.py
      - name: Commit changes
        run: |
          git config --global user.name 'Automation'
          git config --global user.email 'mobile.automation@kiwi.com'
          git commit -am "Update assets" || true
          git push
      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ github.event.inputs.version }}
      - uses: ncipollo/release-action@v1
        with:
          body: ${{ github.event.inputs.changelog }}
          tag: ${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          