name: Update Icons

on:
  schedule:
    - cron: '0 0 * * MON' # every Monday
  workflow_dispatch:
  
env:
  pr_label: "update-icons"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Today env
        run: echo "TODAY=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
      - name: Update Icon Tokens
        run: bash .github/update-icons.sh ${{ env.pr_label }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.PRBOT_APP_ID }}
          private_key: ${{ secrets.PRBOT_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          labels: |
            ${{ env.pr_label }}
          title: Design Tokens Icons Update on ${{ env.TODAY }}
          body: ""
          base: main
          branch: tokens-update-icons